// K1 (SPEC §3.3 training phases): fit, from outcome-labelled pilot rows (evals/voicesig/PILOT-FORMAT.md),
//   (1) the stage-1 CALIBRATION: one isotonic table per head on the rule score (what ladder L1 needs), and
//   (2) the K1 stage-2 head: per-head L2 logistic over the server-side child-z measurements + Tier-T bits, factorised as
//       logit = A·audio + T·text + c (the A/T split is what lets a later embedding branch move A onto the device).
// Every head is trained ONLY on its task outcome (O1..O4, G-VS-LABEL); coder marks are never read here.
// Child-clustered 5-fold CV metrics are reported with the weights. CPU only, seconds per run: no GPU, nothing to tear down.
//
//   node scripts/voicesig/k1-train.mjs <rows.jsonl> --out <head.json>
//
// SAFETY RAIL: rows generated by evals/voicesig/simulate-pilot.mjs carry `sim`; a fit that saw any of them refuses to
// write under models/ (simulated weights must never ship).
import { readFileSync, writeFileSync } from "node:fs";
import { runAdapter } from "../../evals/voicesig/harness.mjs";
import { auroc, clusterFolds, ece, fitLogistic, predictLogistic } from "../../evals/voicesig/metrics.mjs";
import { fitIsotonic, applyIsotonic } from "../../server/voicesig/calibrate.js";

export const AUDIO = ["onsetZ", "pauseZ", "longestPauseZ", "durationZ", "fillerLead", "fillerRuns", "finalRelDb", "qAudio"];
export const TEXT = ["hedge", "fillerLex", "rightToWrong", "idkRecall", "idkNotKnown", "o3History", "bt", "hint", "logWords"];
const HEADS = {
  h1: { rows: (r) => r.verdict === "correct", y: (r) => r.outcomes?.O1 },
  h2: { rows: (r) => !!r.ling?.idk, y: (r) => r.outcomes?.O2 },
  h3: { rows: (r) => r.verdict === "not_yet" || r.verdict === "partial", y: (r) => r.outcomes?.O3 },
  h4: { rows: (r) => r.vs?.state === "rapidGuess", y: (r) => r.outcomes?.O4 },
};
const fin = (x) => typeof x === "number" && Number.isFinite(x);

export function featuresOf(r) {
  const z = r.vs?.z ?? {}, f = r.kv?.f ?? {}, q = r.kv?.q ?? {}, L = r.ling ?? {};
  const zz = (k) => (fin(z[k]) ? z[k] : 0);
  const audio = {
    onsetZ: fin(z.contentOnsetMs) ? z.contentOnsetMs : zz("onsetMs"), pauseZ: zz("pauseFrac"), longestPauseZ: zz("longestPauseMs"), durationZ: zz("durationMs"),
    fillerLead: q.det && fin(f.fillerLeadMs) ? Math.log1p(f.fillerLeadMs / 100) : 0, fillerRuns: q.det && fin(f.fillerRuns) ? Math.min(3, f.fillerRuns) : 0,
    finalRelDb: q.raw && fin(f.finalRelDb) ? f.finalRelDb / 5 : 0, qAudio: fin(q.audio) ? q.audio : 0,
  };
  const text = {
    hedge: L.hedge ? 1 : 0, fillerLex: L.fillerLex ? 1 : 0, rightToWrong: L.repairDir === "right_to_wrong" ? 1 : 0,
    idkRecall: L.idk === "cant_recall" ? 1 : 0, idkNotKnown: L.idk === "not_known" ? 1 : 0, o3History: r.o3History ? 1 : 0,
    bt: fin(r.bt) ? r.bt : 0, hint: (r.hintRung ?? 0) / 4, logWords: Math.log1p(r.words ?? 1),
  };
  return [...AUDIO.map((k) => audio[k]), ...TEXT.map((k) => text[k])];
}

export function train(rowsIn, { l2 = 2 } = {}) {
  const rows = runAdapter(rowsIn).filter((r) => r.vs && !r.vs.abstain);
  const out = { ver: `vs-k1/${new Date().toISOString().slice(0, 10)}`, simulated: rowsIn.some((r) => r.sim), features: { audio: AUDIO, text: TEXT }, heads: {}, calibration: {}, cv: {} };
  for (const [h, def] of Object.entries(HEADS)) {
    const rs = rows.filter((r) => def.rows(r) && (def.y(r) === 0 || def.y(r) === 1));
    const ys = rs.map(def.y);
    if (rs.length < 50 || !ys.includes(0) || !ys.includes(1)) { out.cv[h] = { n: rs.length, skipped: "insufficient" }; continue; }
    const X = rs.map(featuresOf);
    const folds = clusterFolds(rs.map((r) => r.child), 5);
    const pHead = new Array(rs.length).fill(NaN), pCal = new Array(rs.length).fill(NaN);
    const ruleScore = rs.map((r) => r.vs.sE[h] + r.vs.sT[h]);
    for (const fold of folds) {
      const tr = rs.map((_, i) => i).filter((i) => !fold.has(rs[i].child));
      const w = fitLogistic(tr.map((i) => X[i]), tr.map((i) => ys[i]), { l2 });
      const iso = fitIsotonic(tr.map((i) => ruleScore[i]), tr.map((i) => ys[i]));
      rs.forEach((r, i) => { if (fold.has(r.child)) { pHead[i] = predictLogistic(w, X[i]); pCal[i] = applyIsotonic(iso, ruleScore[i]); } });
    }
    const ok = rs.map((_, i) => i).filter((i) => fin(pHead[i]));
    const w = fitLogistic(X, ys, { l2 });
    out.heads[h] = { c: w[0], A: Object.fromEntries(AUDIO.map((k, j) => [k, w[1 + j]])), T: Object.fromEntries(TEXT.map((k, j) => [k, w[1 + AUDIO.length + j]])) };
    out.calibration[h] = fitIsotonic(ruleScore, ys);
    out.cv[h] = {
      n: rs.length, children: new Set(rs.map((r) => r.child)).size, positiveRate: ys.reduce((a, b) => a + b, 0) / ys.length,
      aurocHead: auroc(ok.map((i) => pHead[i]), ok.map((i) => ys[i])), eceHead: ece(ok.map((i) => pHead[i]), ok.map((i) => ys[i])),
      aurocRulesCalibrated: auroc(ok.map((i) => pCal[i]), ok.map((i) => ys[i])), eceRulesCalibrated: ece(ok.map((i) => pCal[i]), ok.map((i) => ys[i])),
    };
  }
  return out;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const outPath = args[args.indexOf("--out") + 1];
  const rows = readFileSync(args[0], "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
  const res = train(rows);
  if (res.simulated && /(^|\/)models\//.test(outPath)) { console.error("refusing: simulated rows never produce shippable weights"); process.exit(3); }
  writeFileSync(outPath, JSON.stringify(res, null, 1));
  console.log(JSON.stringify(res.cv));
}
