// forge3 certification of play pieces (round 3, stream forge): every (family, mode) the play stream registers, in every art
// direction it can wear, generated by the family's OWN generator (code, solver-checked: solve() non-null, shortcut() null),
// rendered as a PlayArtifact on the real Studio stage (PlayStudioRenderer) in the Desk's play-mode boxes (viewports.js
// PLAY_VIEWPORTS, measured live), and judged by the same checks as everything else
// (server/forge3/qa/checks.js; class 4-5 at the 16 px floor). The verdict table is what compose() may offer at a size.
//
//   FORGE3_QA_LOCAL=1 node server/forge3/play-cert.js --harness <built harness dir> [--out server/forge3/certs/play.json]
//     [--shots <dir>] [--seeds 2]
// Levels come from the play coverage file's entries as the play server serves them (coverageLevels below), so the table is
// judged on the levels a child actually gets, in every art direction the family can wear.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { serveHarness, openJudge, launchLocal } from "./qa/render.js";
import { PLAY_VIEWPORTS } from "./qa/viewports.js";
import { QA_VERSION } from "./qa/checks.js";

const here = path.dirname(fileURLToPath(import.meta.url));
export const PLAY_CERT_FILE = path.join(here, "certs", "play.json");

/** A served-quality level for (family, mode): the family's own generator, solvable and shortcut-free, or null. */
export function levelFor(logic, family, mode, { seed = 1, classLevel = 6, grammar = {} } = {}) {
  const req = { family, mode, topicId: `qa-${family}`, skillId: `qa-${family}-${mode}`, classLevel, fade: 1, mis: {}, misMap: {}, grammar, recent: [], seed, goal: undefined };
  let cands = [];
  try { cands = logic.generate(req) ?? []; } catch { return null; }
  for (const c of cands) {
    const lv = c?.level;
    if (!lv || lv.mode !== mode) continue;
    try { if (logic.solve(lv) && !logic.shortcut(lv)) return lv; } catch { /* a candidate that throws is never served */ }
  }
  return null;
}

/**
 * Served levels for a coverage entry, as the play server would serve them to a fresh child of the entry's class: the
 * same session body startSession builds (server/play/start.js), seeds n = 0..k-1, the picker's garam door.
 */
export async function coverageLevels(entry, k = 2) {
  const { currentLevel, entryKey, seedOf } = await import("../play/levels.js");
  const out = [];
  for (let n = 0; n < k; n++) {
    const key = entryKey(entry);
    const s = { childId: `qa-${n}`, key, skillId: entry.skillId, lessonId: null, classLevel: entry.classLevel, fade: 1, lang: "hinglish", childArt: null, lastArt: null,
      mis: {}, pL: undefined, n: 0, seed: seedOf(`qa-${n}`, key, 0), door: "garam", recent: [], hist: null };
    try { const lv = currentLevel(s, entry); if (lv && !out.some((x) => x.levelId === lv.levelId)) out.push(lv); } catch { /* a generator that throws serves nothing */ }
  }
  return out;
}

/**
 * Add each cell's SERVING verdict (certify.js servesView: a classes 4-5 level whose only failure is the 16 px young floor,
 * with its smallest text ≥ 14 px, may still be served) from the samples. Strict verdicts stay as judged.
 */
export function servingVerdicts(table) {
  const { servesView } = SERVE;
  for (const [key, cells] of Object.entries(table.pieces ?? {})) for (const [cellKey, cell] of Object.entries(cells)) {
    if (!cell?.byViewport) continue;
    const [art, band] = cellKey.split("@c");
    const S = (table.samples ?? []).filter((x) => x.key === key && x.art === art && (x.classLevel <= 5 ? "4" : "7") === band && !x.noLevel);
    cell.serveByViewport = Object.fromEntries(Object.keys(cell.byViewport).map((vp) => [vp, S.length > 0 && S.every((x) => servesView({
      pass: !!x.byViewport?.[vp], fails: (x.fails ?? []).filter((f) => f.startsWith(`${vp}:`)).map((f) => f.slice(vp.length + 1)), minPx: x.minPx?.[vp] }))]));
  }
  return table;
}
import * as SERVE from "./certify.js";

if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  const arg = (k, d) => { const i = argv.indexOf(`--${k}`); return i >= 0 ? argv[i + 1] : d; };
  const out = arg("out", PLAY_CERT_FILE);
  const shots = arg("shots", null);
  const seeds = Number(arg("seeds", "2")) || 2;
  const { FAMILY_ARTS } = await import("../../shared/play.ts");
  const { coverage } = await import("../play/levels.js");
  const entries = coverage().entries ?? [];
  const { server, base } = await serveHarness(arg("harness"));
  const browser = await launchLocal();
  const judge = await openJudge({ browser, base });
  const table = { v: 2, qa: QA_VERSION, at: new Date().toISOString(), viewports: PLAY_VIEWPORTS.map((v) => v.vp), source: "data/play/coverage.json entries, served levels (garam door), seeds 0..k-1", pieces: {}, samples: [] };
  let shot = 0;
  for (const entry of entries) {
    const key = `${entry.family}/${entry.mode}`;
    const band = entry.classLevel <= 5 ? 4 : 7;
    const levels = await coverageLevels(entry, seeds);
    if (!levels.length) { table.samples.push({ topicId: entry.topicId, key, goal: entry.goal, noLevel: true }); console.log(`${entry.topicId} ${key}: no served level`); continue; }
    for (const level of levels) for (const art of FAMILY_ARTS[entry.family] ?? []) {
      // judged as the child sees it: a PlayArtifact on the REAL Studio stage (PlayStudioRenderer → PlaySession) in the Desk's
      // play-mode box, its level fetch answered by the harness (the first certification rendered PlayStage directly, whose
      // own header and teacher strip the Desk does not show)
      const logic = (await import("../../src/play/families/index.ts")).logicFor(level.family, level.mode);
      let boardTwin = null;
      try { const b = logic.board(level, logic.init(level)); boardTwin = { board: { title: b.title, lines: b.lines } }; } catch { boardTwin = null; }
      const artifact = { kind: "play", stage: { w: 360, h: 576 }, play: { sessionId: "qa", family: level.family, mode: level.mode, skillId: level.skillId, topicId: level.topicId, art, levelId: level.levelId }, ...(boardTwin ? { boardTwin } : {}) };
      const r = await judge.judge(artifact, { viewports: PLAY_VIEWPORTS, young: entry.classLevel <= 5, playLevel: { level, art: { art, reason: "qa" } },
        shotDir: shots && shot++ % 7 === 0 ? `${shots}/${key.replace("/", "_")}` : undefined, shotTag: `${entry.topicId}-${art}` });
      const cell = ((table.pieces[key] ??= {})[`${art}@c${band}`] ??= { byViewport: Object.fromEntries(PLAY_VIEWPORTS.map((v) => [v.vp, true])), n: 0, fails: [] });
      cell.n++;
      for (const v of r.views) if (!v.verdict.pass) { cell.byViewport[v.vp] = false; for (const f of v.verdict.fails) if (cell.fails.length < 12 && !cell.fails.includes(`${v.vp}:${f}`)) cell.fails.push(`${v.vp}:${f}`); }
      table.samples.push({ topicId: entry.topicId, key, goal: entry.goal, levelId: level.levelId, art, classLevel: entry.classLevel, byViewport: r.piece.byViewport,
        fails: r.piece.fails.slice(0, 6), minPx: Object.fromEntries(r.views.map((v) => [v.vp, v.verdict.stats.minPx])), fill: Object.fromEntries(r.views.map((v) => [v.vp, v.verdict.stats.fill])) });
      console.log(`${entry.topicId} ${key} ${art} c${entry.classLevel}: ${JSON.stringify(r.piece.byViewport)} ${r.piece.fails.slice(0, 3).join(" ")}`);
    }
  }
  await judge.close(); await browser.close(); server.close();
  servingVerdicts(table);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, JSON.stringify(table, null, 1));
  const S = table.samples.filter((x) => !x.noLevel);
  console.log(`samples ${S.length}; passing at every size ${S.filter((x) => Object.values(x.byViewport).every(Boolean)).length}; by size ${JSON.stringify(Object.fromEntries(PLAY_VIEWPORTS.map((v) => [v.vp, S.filter((x) => x.byViewport[v.vp]).length])))} → ${out}`);
}
