"""E-GNM1 step 1: fit GNM Head v3.0's identity controls to the teal reference portraits.

Inputs (read-only, shared with the merged run): art/character/bakeoff/merged/refs/teal/{landmarks.json, *.png}
(MediaPipe Face Landmarker 478 points per portrait, generated by taxila-image, see refs.json there).

Model landmark i = GNM bind vertex vert[i] + (reference[i] - template[vert[i]]): XR Blocks' MediaPipe<->GNM
correspondence and its "differential" reference cloud, so the landmarker's own placement bias (6.7 mm rms in depth on
the neutral GNM face) cancels instead of being absorbed into the identity.
Cameras: one scaled-orthographic camera per view (rotation vector, scale, 2D offset).
Unknowns: 170 head + 3 eyeball identity components (unit-std units, prior N(0, 1/lam^2), lam 2 chosen on the held-out
views); a shared nuisance expression (8 lower-face + 6 + 6 eye components, prior N(0, 1)) so the portraits' relaxed
expression is not absorbed into the identity; it is dropped from the rest shape.
Terms (all in % of the view's IOD = camera scale x the 3D outer-eye-corner distance; a 2D landmark IOD collapses at
profile and overweighted the profile terms 5-10x, measured):
  landmarks   2D reprojection on front / q45_left / q45_right, sigma 1 % IOD; MediaPipe's face-contour points
              down-weighted (x0.5 front, x0.25 on the 3/4 views: they slide along the silhouette)
  skin edges  the outermost SKIN-mask pixel per image row (a hue/chroma window: skin vs grey seamless, black hair, teal
              kurti) against the model's outermost projected vertex in that row (ICP, re-picked each pass), sigma 1.5 %:
              both sides from eye to chin on front and 3/4 views (ears, cheeks, jaw), the leading edge forehead to
              throat on profile90_left / profile90_right
  profiles    MediaPipe fails at full profile (its yaw reads 58-60 on near-90-degree portraits), so each profile camera
              comes from the silhouette alone: a yaw / pitch / roll grid with a 2D scale+offset ICP of the model's
              leading-edge curve onto the portrait's, re-searched every pass; no profile landmarks are used
TRAIN views: front, q45_left, q45_right (+ the two profiles' silhouettes). HELD OUT: q3_left, q3_right (reported
only: 2D reprojection NME of the fitted model with a camera-only solve, the views the merged fit loop held out).
    python fit.py [--lam 2.0] [--sil 1.0] [--out art/character/bakeoff/gnm/fit/teal.json]"""
import argparse, json, math, os, time
import numpy as np
from scipy.optimize import least_squares
from scipy.spatial.transform import Rotation as Rot
from PIL import Image
import gnm_model as G

ap = argparse.ArgumentParser()
ap.add_argument("--lam", type=float, default=2.0, help="prior weight multiplier on the identity coefficients")
ap.add_argument("--sil", type=float, default=1.0, help="silhouette term gain (0 = off)")
ap.add_argument("--nid", type=int, default=170, help="leading head identity components fitted")
ap.add_argument("--look", default="teal")
ap.add_argument("--out", default=None)
a = ap.parse_args()
PTH = G.paths(a.look)
a.out = a.out or PTH["FIT"]
REFD = PTH["REFD"]
LM = json.load(open(os.path.join(REFD, "landmarks.json")))
RG = json.load(open(os.path.join(G.ROOT, "art/character/bakeoff/merged/mp_regions.json")))
m = G.GNM()
C = G.mp_correspondence()
mpi, vid = C["landmarks"], C["vertices"]
bias = C["reference"] - m.T[vid]
oval = np.isin(mpi, RG["oval"])
TRAIN = ["front", "q45_left", "q45_right"]
HELD = ["q3_left", "q3_right"]
PROF = ["profile90_left", "profile90_right"]

idx_head = m.id_index("head_")[: a.nid]
idx_eye = m.id_index("eyes_")
IDX = np.concatenate([idx_head, idx_eye])
NUI = np.concatenate([m.ex_index("lower_face_region_")[:8], m.ex_index("left_eye_region_")[:6], m.ex_index("right_eye_region_")[:6]])
Bl_id = m.Bid[IDX][:, vid, :].astype(np.float64)        # (K, N, 3)
Bl_ex = m.Bex[NUI][:, vid, :].astype(np.float64)
skin_ext = m.group("skin_exterior") & ~m.group("ears")
FRONTISH = np.where(m.group("skin_exterior") & (m.T[:, 2] > -0.03) & (m.T[:, 1] > 0.09))[0]   # silhouette candidates: front 2/3 of head + neck, ears included
B_front_id = m.Bid[IDX][:, FRONTISH, :].astype(np.float64)
B_front_ex = m.Bex[NUI][:, FRONTISH, :].astype(np.float64)


IODV = {}     # per-view IOD in px = camera scale x the 3D outer-eye-corner distance (set each outer pass): a 2D landmark
              # IOD collapses at profile (both corners project together), which overweighted the profile terms 5-10x


def obs(view):
    L = LM.get(view)
    if not L:                                                # a profile with no MediaPipe face: silhouette only
        return None, IODV.get(view, 100.0)
    P = np.array(L["lm"])[:, :2]
    iod = IODV.get(view) or np.linalg.norm(P[33] - P[263])
    return P[mpi], iod


def lm_points(cid, cex):
    return m.T[vid] + bias + np.tensordot(cid, Bl_id, 1) + np.tensordot(cex, Bl_ex, 1)


def front_points(cid, cex):
    return m.T[FRONTISH] + np.tensordot(cid, B_front_id, 1) + np.tensordot(cex, B_front_ex, 1)


def project(X, cam):
    R = Rot.from_rotvec(cam[:3]).as_matrix()
    Y = X @ R.T
    return np.stack([cam[3] * Y[:, 0] + cam[4], -cam[3] * Y[:, 1] + cam[5]], 1)


def init_cam(X, U):
    """Scaled orthographic camera from 3D->2D correspondences (affine fit, then the nearest scaled rotation)."""
    Xc, Uc = X - X.mean(0), U - U.mean(0)
    Uc = Uc * np.array([1, -1])
    A, *_ = np.linalg.lstsq(Xc, Uc, rcond=None)           # (3, 2): u = X A
    M = A.T                                              # rows = s * r1, s * r2
    s = 0.5 * (np.linalg.norm(M[0]) + np.linalg.norm(M[1]))
    r1, r2 = M[0] / np.linalg.norm(M[0]), M[1]
    r2 = r2 - r1 * (r1 @ r2); r2 /= np.linalg.norm(r2)
    R = np.stack([r1, r2, np.cross(r1, r2)])
    U0, _, Vt = np.linalg.svd(R); R = U0 @ Vt
    rv = Rot.from_matrix(R).as_rotvec()
    p = project(X, np.r_[rv, s, 0, 0])
    t = (U - p).mean(0)
    return np.r_[rv, s, t]


# ---------------------------------------------------------------- silhouettes (portrait SKIN mask edges)
def skin_mask(path):
    """Skin pixels by colour: the portraits are skin on a light grey seamless, black hair and a teal kurti, so a
    hue/chroma window separates skin cleanly (checked by eye on all 10 views)."""
    im = np.asarray(Image.open(path).convert("RGB")).astype(np.float64) / 255
    r, g, b = im[..., 0], im[..., 1], im[..., 2]
    mx, mn = im.max(2), im.min(2)
    hue = np.degrees(np.arctan2(np.sqrt(3) * (g - b), 2 * r - g - b)) % 360
    return ((mx - mn) > 0.10) & ((hue < 48) | (hue > 345)) & (mx > 0.22) & (r > g) & (g >= b * 0.9)


def edges(view):
    """[(rows, xs, side, weight)]: the outermost skin edge per image row.
    front / 3/4 views: both sides, eye row to chin (ears, cheeks, jaw; above the ears the hair covers the temples);
    profiles: the leading (face-side) edge, forehead to throat."""
    mask = skin_mask(os.path.join(REFD, f"{view}.png"))
    if LM.get(view):
        L = np.array(LM[view]["lm"])
        eye_y = L[[159, 386]][:, 1].mean(); brow_y = L[[105, 334, 9]][:, 1].min(); chin_y = L[152][1]
    else:
        # round 2: MediaPipe finds NO face on some generated profiles (slate both, plum left): the brow / chin rows come
        # from the front view's landmarks scaled into this view's skin-mask extent (same framing for the whole set)
        Lf = np.array(LM["front"]["lm"]); mf = skin_mask(os.path.join(REFD, "front.png"))
        rf = np.where(mf.any(1))[0]; rv_ = np.where(mask.any(1))[0]
        sc_ = (rv_[-1] - rv_[0]) / max(1, rf[-1] - rf[0])
        tr_ = lambda y: rv_[0] + (y - rf[0]) * sc_
        brow_y = tr_(Lf[[105, 334, 9]][:, 1].min()); chin_y = tr_(Lf[152][1]); eye_y = tr_(Lf[[159, 386]][:, 1].mean())
        L = None
    out = []
    if view in PROF:
        side = (1 if L[1][0] > L[:, 0].mean() else -1) if L is not None else (1 if view.endswith("left") else -1)
        sides, rows = [side], np.arange(int(brow_y - 0.45 * (chin_y - brow_y)), int(chin_y + 0.55 * (chin_y - brow_y)), 4)
    else:
        sides, rows = [1, -1], np.arange(int(eye_y), int(chin_y), 4)
    for sd in sides:
        xs = []
        for r in rows:
            cols = np.where(mask[r])[0]
            xs.append(np.nan if not len(cols) else (cols.max() if sd > 0 else cols.min()))
        out.append((rows, np.array(xs, float), sd, 1.0))
    return out


SIL = {v: edges(v) for v in TRAIN + PROF if LM.get(v) or (v in PROF and os.path.exists(os.path.join(REFD, f"{v}.png")))}
# ---------------------------------------------------------------- parameter vector
K, E = len(IDX), len(NUI)
views = list(TRAIN)                                       # cameras solved inside the least squares
PROFV = [v for v in PROF if v in SIL]
PSIDE = {v: SIL[v][0][2] for v in PROFV}
nv = len(views)
X0 = lm_points(np.zeros(K), np.zeros(E))
p0 = np.concatenate([np.zeros(K), np.zeros(E)] + [init_cam(X0, obs(v)[0]) for v in views])
assign = {}
PCAM = {}


def unpack(p):
    return p[:K], p[K:K + E], p[K + E:].reshape(nv, 6)


def edge_curve(F, R, side, binw=0.0015):
    """The model's leading edge in a side view at unit scale: per height bin the outermost projected point."""
    Y = F @ R.T
    u, v = Y[:, 0] * side, -Y[:, 1]
    b = np.floor(v / binw).astype(int)
    o = np.lexsort((-u, b))
    first = np.r_[True, b[o][1:] != b[o][:-1]]
    k = o[first]
    return np.stack([u[k] * side, v[k]], 1), k


def search_profile_cam(v, cid, cex, around=None):
    """MediaPipe fails at full profile, so the profile cameras come from the silhouette alone: a grid over yaw / pitch /
    roll (around +-88 deg yaw) with, for each, a 2D ICP (scale + offset) of the model's leading-edge curve onto the
    portrait's skin-mask leading edge; the best mean distance wins, then a finer grid around it."""
    rows, xs, side, _ = SIL[v][0]
    ok = ~np.isnan(xs)
    Q = np.stack([xs[ok], rows[ok].astype(float)], 1)
    F = front_points(cid, cex)
    from scipy.spatial import cKDTree

    def score(yaw, pit, rol):
        R = Rot.from_euler("YXZ", [yaw, pit, rol], degrees=True).as_matrix()
        M, k = edge_curve(F, R, side)
        sc = (np.ptp(Q[:, 1]) / max(1e-6, np.ptp(M[:, 1]))) * 0.8
        t = Q.mean(0) - sc * M.mean(0)
        for _ in range(20):
            P = sc * M + t
            d, j = cKDTree(P).query(Q)
            A = M[j]; Am, Qm = A.mean(0), Q.mean(0)
            sc = ((A - Am) * (Q - Qm)).sum() / max(1e-12, ((A - Am) ** 2).sum())
            t = Qm - sc * Am
        d, _ = cKDTree(sc * M + t).query(Q)
        return float(np.mean(d)), R, sc, t

    best = None
    if around is None:
        grid = [(side * y, p_, r_) for y in range(74, 99, 4) for p_ in range(-12, 13, 4) for r_ in range(-8, 9, 4)]
    else:
        y0, p0_, r0 = around
        grid = [(y0 + dy, p0_ + dp, r0 + dr) for dy in (-2, 0, 2) for dp in (-2, 0, 2) for dr in (-2, 0, 2)]
    for g in grid:
        sc_ = score(*g)
        if best is None or sc_[0] < best[0][0]:
            best = (sc_, g)
    if around is None:
        y0, p0_, r0 = best[1]
        for g in [(y0 + dy, p0_ + dp, r0 + dr) for dy in (-2, -1, 0, 1, 2) for dp in (-2, 0, 2) for dr in (-2, 0, 2)]:
            sc_ = score(*g)
            if sc_[0] < best[0][0]:
                best = (sc_, g)
    (d, R, sc, t), g = best
    # the camera in this file's convention: u = s (R X)_x + tx, v = -s (R X)_y + ty
    return np.r_[Rot.from_matrix(R).as_rotvec(), sc, t], g, d


IOD3 = float(np.linalg.norm(m.T[vid[list(mpi).index(33)]] - m.T[vid[list(mpi).index(263)]]))


def pick_edges(p):
    cid, cex, cams = unpack(p)
    F = front_points(cid, cex)
    for v in PROFV:
        PCAM[v], g, d = search_profile_cam(v, cid, cex, PCAM.get(v + ":g"))
        PCAM[v + ":g"] = g
        PCAM[v + ":d"] = d
    for v in views + PROFV:
        cam = PCAM[v] if v in PROFV else cams[views.index(v)]
        IODV[v] = float(cam[3] * IOD3)
        uv = project(F, cam)
        assign[v] = []
        for rows, xs, side, w in SIL[v]:
            pick = []
            for r, x in zip(rows, xs):
                sel = np.where(np.abs(uv[:, 1] - r) < 3.0)[0]
                pick.append(-1 if (not len(sel) or np.isnan(x)) else sel[np.argmax(uv[sel, 0] * side)])
            assign[v].append(np.array(pick))


BLm = np.concatenate([Bl_id, Bl_ex])                      # (K+E, N, 3) landmark basis
BFr = np.concatenate([B_front_id, B_front_ex])            # (K+E, F, 3) front-edge basis


def blocks(p):
    """Residual blocks: (camera index j or -1 for a fixed profile camera, cam, rest points X (n,3), basis (K+E,n,3),
    target (n,2) or x-only (n,), weight (n,))."""
    cid, cex, cams = unpack(p)
    th = np.r_[cid, cex]
    X = m.T[vid] + bias + np.tensordot(th, BLm, 1)
    out = []
    for v in views + PROFV:
        U, iod = obs(v)
        j = views.index(v) if v in views else -1
        cam = cams[j] if j >= 0 else PCAM[v]
        if v in TRAIN:
            w = np.where(oval, 0.5 if v == "front" else 0.25, 1.0) * 100 / iod / 1.0
            out.append((j, cam, X, BLm, U, w))
        if a.sil == 0 or v not in assign:
            continue
        for (rows, xs, side, wt), pk in zip(SIL[v], assign[v]):
            ok = (pk >= 0) & ~np.isnan(xs)
            F = m.T[FRONTISH[pk[ok]]] + np.tensordot(th, BFr[:, pk[ok]], 1)
            out.append((j, cam, F, BFr[:, pk[ok]], xs[ok], np.full(ok.sum(), 100 / iod / 1.5 * a.sil * wt / math.sqrt(max(1, ok.sum() / 40)))))
    return th, cams, out


def _blk_res(X, cam, T, w):
    uv = project(X, cam)
    return ((uv[:, 0] - T) * w) if T.ndim == 1 else ((uv - T) * w[:, None]).ravel()


def residuals(p):
    th, cams, bl = blocks(p)
    r = [_blk_res(X, cam, T, w) for j, cam, X, B, T, w in bl]
    r.append(th[:K] * a.lam); r.append(th[K:] * 1.0)
    return np.concatenate(r)


def jac(p):
    th, cams, bl = blocks(p)
    rows = []
    NP = len(p)
    for j, cam, X, B, T, w in bl:
        R = Rot.from_rotvec(cam[:3]).as_matrix()
        s = cam[3]
        du = s * np.tensordot(B, R[0], ([2], [0])).T              # (n, K+E)
        dv = -s * np.tensordot(B, R[1], ([2], [0])).T
        n = X.shape[0]
        if T.ndim == 1:
            Jt = du * w[:, None]
        else:
            Jt = np.empty((2 * n, K + E)); Jt[0::2] = du * w[:, None]; Jt[1::2] = dv * w[:, None]
        Jb = np.zeros((Jt.shape[0], NP)); Jb[:, :K + E] = Jt
        if j >= 0:
            r0 = _blk_res(X, cam, T, w)
            for q in range(6):
                c2 = cam.copy(); h = 1e-6 if q < 3 else (1e-4 * max(1.0, abs(cam[3])) if q == 3 else 1e-3)
                c2[q] += h
                Jb[:, K + E + 6 * j + q] = (_blk_res(X, c2, T, w) - r0) / h
        rows.append(Jb)
    P = np.zeros((K + E, NP)); P[:K, :K] = np.eye(K) * a.lam; P[K:, K:K + E] = np.eye(E)
    rows.append(P)
    return np.vstack(rows)


t0 = time.time()
p = p0
for outer in range(4):
    pick_edges(p)
    r = least_squares(residuals, p, jac=jac, method="trf", x_scale="jac", max_nfev=100)
    p = r.x
    print(f"[fit] pass {outer}: cost {r.cost:.1f}  profile cams {[(PCAM[v + ':g'], round(PCAM[v + ':d'], 1)) for v in PROFV]} ({time.time() - t0:.0f} s)", flush=True)
cid, cex, cams = unpack(p)


# ---------------------------------------------------------------- report: per-view 2D reprojection NME (interior)
def view_err(v, cam=None):
    U, iod = obs(v)
    X = lm_points(cid, cex)
    if cam is None:     # held-out: camera only, shape frozen
        c0 = init_cam(X[~oval], U[~oval])
        cam = least_squares(lambda c: ((project(X, c) - U)[~oval] / iod).ravel(), c0).x
    e = np.linalg.norm(project(X, cam) - U, axis=1) / iod * 100
    return {"interiorNME": round(float(e[~oval].mean()), 2), "all": round(float(e.mean()), 2),
            "yawDeg": round(float(math.degrees(Rot.from_rotvec(cam[:3]).as_euler("YXZ")[0])), 1)}, cam


rep = {}
for j, v in enumerate(views):
    if v in TRAIN:
        rep[v] = view_err(v, cams[j])[0]
for v in HELD:
    rep[v + " (held out)"] = view_err(v)[0]
sil = {}
pick_edges(p)
for v in views + PROFV:
    cam = PCAM[v] if v in PROFV else cams[views.index(v)]
    iod = obs(v)[1]; F = front_points(cid, cex); uv = project(F, cam)
    for (rows, xs, side, wt), pk in zip(SIL[v], assign[v]):
        ok = (pk >= 0) & ~np.isnan(xs)
        e = uv[pk[ok], 0] - xs[ok]
        sil[f"{v}:{'R' if side > 0 else 'L'}"] = {"meanAbsPctIOD": round(float(np.abs(e).mean() / iod * 100), 2), "rows": int(ok.sum())}
    sil[v + ":yawDeg"] = round(float(math.degrees(Rot.from_rotvec(cam[:3]).as_euler("YXZ")[0])), 1)
# a no-identity baseline (template + cameras only) for scale
full = np.zeros(len(m.id_names)); full[IDX] = cid
ex_full = np.zeros(len(m.ex_names)); ex_full[NUI] = cex
V = m.bind(full)
eyeL, eyeR = m.joints(full)[2], m.joints(full)[3]
out = {"method": __doc__.split("\n")[0], "date": time.strftime("%Y-%m-%d"), "lam": a.lam, "sil": a.sil, "nid": a.nid,
       "identity": full.round(5).tolist(), "nuisanceExpression": ex_full.round(5).tolist(),
       "train": TRAIN, "heldOut": HELD, "silhouetteViews": list(SIL), "reprojection": rep, "silhouette": sil,
       "cameras": {**{v: cams[j].round(6).tolist() for j, v in enumerate(views)}, **{v: PCAM[v].round(6).tolist() for v in PROFV}},
       "coeffAbsMax": round(float(np.abs(cid).max()), 2), "coeffRms": round(float(np.sqrt((cid ** 2).mean())), 3),
       "head": {"interocularMM": round(float(np.linalg.norm(eyeL - eyeR) * 1000), 1),
                "heightMM": round(float((V[:, 1].max() - V[:, 1].min()) * 1000), 1),
                "widthMM": round(float((V[:, 0].max() - V[:, 0].min()) * 1000), 1)},
       "seconds": round(time.time() - t0)}
os.makedirs(os.path.dirname(a.out), exist_ok=True)
json.dump(out, open(a.out, "w"), indent=1)
print(json.dumps({k: out[k] for k in ("reprojection", "silhouette", "coeffAbsMax", "coeffRms", "head")}, indent=1))
