"""Garments, accessories and the hair bun, generated by script from the character's own bust surface.

Garments are offset shells of the skin below a per-look neckline (no cloth simulation, AVATAR S9: unmorphed, split
at the collar), with an extruded rolled edge so the fabric reads as having thickness. Each shell carries per-vertex
attributes the texture stage paints from: `gLayer` (0 inner, 1 outer, 2 accessory), `gEdge` (distance in metres to
the nearest open edge, for piping / borders / hems), and cylindrical UVs so weaves and checks keep a constant scale.
"""
import math
import numpy as np
import bpy, bmesh
from mathutils import Vector
from mpfb_env import co, smoothstep, delete_verts

ACC_PATCH = {"metal": (0.905, 0.955), "gold": (0.955, 0.955), "lens": (0.905, 0.905)}   # uv texel centres in the garment atlas


def _cyl(P, ctr):
    th = np.arctan2(P[:, 0] - ctr[0], -(P[:, 1] - ctr[1]))      # 0 = front, +pi/2 = character's left
    return th


def _shell(src, faces_mask, offset, name):
    """Duplicate the faces of `src` (an object) where faces_mask, offset along vertex normals, return the object."""
    me = src.data
    P = co(me)
    N = np.empty(len(me.vertices) * 3)
    me.vertices.foreach_get("normal", N)
    N = N.reshape(-1, 3)
    bm = bmesh.new()
    vmap = {}
    for i, p in enumerate(me.polygons):
        if not faces_mask[i]:
            continue
        vs = []
        for vi in p.vertices:
            if vi not in vmap:
                vmap[vi] = bm.verts.new(Vector(P[vi] + N[vi] * offset))
            vs.append(vmap[vi])
        bm.faces.new(vs)
    out = bpy.data.meshes.new(name)
    bm.to_mesh(out)
    bm.free()
    ob = bpy.data.objects.new(name, out)
    bpy.context.collection.objects.link(ob)
    return ob, np.array(sorted(vmap, key=lambda k: vmap[k].index)) if False else None


def _edge_distance(ob):
    """Graph distance (metres) from every vertex to the nearest boundary vertex (Dijkstra over mesh edges)."""
    import heapq
    me = ob.data
    P = co(me)
    bm = bmesh.new()
    bm.from_mesh(me)
    bnd = [v.index for v in bm.verts if v.is_boundary]
    adj = [[] for _ in range(len(P))]
    for e in bm.edges:
        a, b = e.verts[0].index, e.verts[1].index
        L = float(np.linalg.norm(P[a] - P[b]))
        adj[a].append((b, L))
        adj[b].append((a, L))
    bm.free()
    dist = np.full(len(P), 1e9)
    hq = []
    for b in bnd:
        dist[b] = 0
        hq.append((0.0, b))
    heapq.heapify(hq)
    while hq:
        d, u = heapq.heappop(hq)
        if d > dist[u]:
            continue
        for v, L in adj[u]:
            nd = d + L
            if nd < dist[v]:
                dist[v] = nd
                heapq.heappush(hq, (nd, v))
    return dist, set(bnd)


def _rolled_edge(ob, inward, keep_low_z):
    """Extrude the open top/front edges toward the body by `inward` so the fabric edge has visible thickness."""
    me = ob.data
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.normal_update()
    edges = [e for e in bm.edges if e.is_boundary and min(v.co.z for v in e.verts) > keep_low_z]
    if edges:
        ret = bmesh.ops.extrude_edge_only(bm, edges=edges)
        nv = [g for g in ret["geom"] if isinstance(g, bmesh.types.BMVert)]
        for v in nv:
            n = v.normal if v.normal.length > 0 else Vector((0, 0, 1))
            v.co -= n * inward
    bm.to_mesh(me)
    bm.free()


def _attr(ob, name, arr):
    a = ob.data.attributes.get(name) or ob.data.attributes.new(name, "FLOAT", "POINT")
    a.data.foreach_set("value", np.asarray(arr, np.float32))


def _cyl_uv(ob, ctr, layer, z0, z1):
    """Cylindrical UV in a per-layer band of the garment atlas: u = theta, v = height (constant texel scale)."""
    me = ob.data
    P = co(me)
    th = _cyl(P, ctr)
    uvl = me.uv_layers.new(name="UVMap")
    v0 = 0.02 + 0.44 * layer
    for p in me.polygons:
        for li, vi in zip(p.loop_indices, p.vertices):
            u = 0.02 + 0.86 * (th[vi] + math.pi) / (2 * math.pi)
            v = v0 + 0.42 * np.clip((P[vi, 2] - z0) / (z1 - z0), 0, 1)
            uvl.data[li].uv = (u, v)


def make_garments(skin, look, J, report):
    """Build the look's garment layers from the bust skin; delete the skin they cover. Returns [objects]."""
    g = look["garment"]
    P = co(skin.data)
    ctr = np.array([0.0, J["joint-neck"][1] + 0.005])
    th = _cyl(P, ctr)
    z_clav = J["joint-l-clavicle"][2]
    zmin = P[:, 2].min()
    front = np.clip(np.cos(th), 0, 1)
    kind = g["kind"]
    base = z_clav + 0.045
    if kind == "kurti-jacket":
        z_col = base - 0.05 * front ** 2
    elif kind == "shirt-tee":
        z_col = base + 0.004 - 0.026 * front ** 3
    else:  # saree blouse
        z_col = base - 0.05 * front ** 2
    covered_v = P[:, 2] < z_col
    polys = skin.data.polygons
    fmask = np.array([all(covered_v[i] for i in p.vertices) for p in polys])
    objs = []

    inner, _ = _shell(skin, fmask, 0.0042, "g_inner")
    _rolled_edge(inner, 0.003, zmin + 0.015)
    objs.append((inner, 0))

    def outer_shell(open_half, offset, name, stand=0.0, extra_mask=None):
        th_open = np.radians(open_half)
        m = covered_v & (np.abs(th) > th_open + 0.25 * np.clip((z_col - P[:, 2]) / 0.12, 0, 1))
        if extra_mask is not None:
            m = extra_mask
        fm = np.array([all(m[i] for i in p.vertices) for p in polys])
        ob, _ = _shell(skin, fm, offset, name)
        if stand > 0:   # a standing collar: extrude the neck-side boundary up and slightly out
            bm = bmesh.new()
            bm.from_mesh(ob.data)
            edges = [e for e in bm.edges if e.is_boundary and all(v.co.z > z_clav - 0.01 for v in e.verts)]
            if edges:
                ret = bmesh.ops.extrude_edge_only(bm, edges=edges)
                for v in [x for x in ret["geom"] if isinstance(x, bmesh.types.BMVert)]:
                    d = Vector((v.co.x - ctr[0], v.co.y - ctr[1], 0))
                    d = d.normalized() if d.length > 0 else Vector((0, 1, 0))
                    v.co += Vector((0, 0, stand)) + d * (0.006)
            bm.to_mesh(ob.data)
            bm.free()
        _rolled_edge(ob, 0.004, zmin + 0.015)
        return ob

    if kind == "kurti-jacket":
        objs.append((outer_shell(28, 0.011, "g_outer", stand=0.022), 1))
    elif kind == "shirt-tee":
        objs.append((outer_shell(16, 0.009, "g_outer", stand=0.03), 1))
    else:
        # saree pallu: a band from the right lower chest over the LEFT shoulder and down the back
        a = np.array([-0.13, J["joint-neck"][1] - 0.12, zmin + 0.02])        # right lower chest (front)
        b = np.array([0.085, J["joint-l-clavicle"][1], z_clav + 0.045])       # over the left shoulder
        c = np.array([0.02, J["joint-l-clavicle"][1] + 0.16, zmin + 0.02])    # down the back
        def seg_d(p, s0, s1):
            v = s1 - s0
            t = np.clip(((p - s0) @ v) / (v @ v), 0, 1)
            return np.linalg.norm(p - (s0 + t[:, None] * v), axis=1)
        d = np.minimum(seg_d(P, a, b), seg_d(P, b, c))
        band = (d < 0.075) & (P[:, 2] < z_col + 0.035)
        objs.append((outer_shell(0, 0.010, "g_outer", extra_mask=band), 1))

    # delete the skin the garment covers (keep a 1.5 cm skirt under the collar so no gap shows on motion)
    under = P[:, 2] < (z_col - 0.015)
    delete_verts(skin, under)

    zs = (zmin, z_clav + 0.08)
    out = []
    for ob, layer in objs:
        dist, _ = _edge_distance(ob)
        _attr(ob, "gEdge", np.minimum(dist, 0.2))
        _attr(ob, "gLayer", np.full(len(ob.data.vertices), layer))
        _cyl_uv(ob, ctr, layer, *zs)
        out.append(ob)
    report["garment"] = {"kind": kind, "collarBaseZ": float(base)}
    return out


def _uv_patch(ob, uv):
    me = ob.data
    uvl = me.uv_layers.get("UVMap") or me.uv_layers.new(name="UVMap")
    for li in range(len(me.loops)):
        uvl.data[li].uv = uv


def make_glasses(look, eyeC, eyeR, earsP):
    """Round thin-rim glasses: two torus rims, a bridge, two temples to the ears. Rigid to the head."""
    gl = look["accessory"]["glasses"]
    R = gl["radius"]
    bm = bmesh.new()
    rims = {}
    for side, sg in (("L", 1), ("R", -1)):
        c = np.array(eyeC[side]) + np.array([sg * 0.002, -(eyeR + 0.012), 0.0015])
        rims[side] = c
        t = bmesh.ops.create_circle(bm, cap_ends=False, radius=R, segments=40)
        ring = t["verts"]
        # orient: circle is in XY; rotate to XZ (facing -Y) and move
        for v in ring:
            x, y, z = v.co
            v.co = Vector((c[0] + x, c[1], c[2] + y))
    me = bpy.data.meshes.new("rims")
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new("glasses", me)
    bpy.context.collection.objects.link(ob)
    # give the rim circles thickness with a skin-like tube: convert edges to a curve bevel
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.ops.object.convert(target="CURVE")
    ob.data.bevel_depth = 0.0011
    ob.data.bevel_resolution = 1
    # bridge + temples as curves too
    cu = bpy.data.curves.new("frame", "CURVE")
    cu.dimensions = "3D"
    cu.bevel_depth = 0.0009
    cu.bevel_resolution = 1

    def poly(points):
        s = cu.splines.new("POLY")
        s.points.add(len(points) - 1)
        for p, q in zip(s.points, points):
            p.co = (*q, 1)

    L, Rr = rims["L"], rims["R"]
    poly([L + np.array([-R, 0, 0.004]), (L + Rr) / 2 + np.array([0, -0.002, 0.009]), Rr + np.array([R, 0, 0.004])])
    for side, sg in (("L", 1), ("R", -1)):
        c = rims[side]
        ear = earsP[side]
        start = c + np.array([sg * R, 0, 0.004])
        poly([start, start + np.array([sg * 0.008, 0.012, 0.0]), np.array([ear[0] + sg * 0.004, ear[1] - 0.004, ear[2] + 0.012]),
              np.array([ear[0] + sg * 0.002, ear[1] + 0.012, ear[2] - 0.004])])
    fo = bpy.data.objects.new("frame", cu)
    bpy.context.collection.objects.link(fo)
    bpy.ops.object.select_all(action="DESELECT")
    fo.select_set(True)
    bpy.context.view_layer.objects.active = fo
    bpy.ops.object.convert(target="MESH")
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.convert(target="MESH")
    fo.select_set(True)
    bpy.ops.object.join()
    _uv_patch(ob, ACC_PATCH["metal"])
    _attr(ob, "gLayer", np.full(len(ob.data.vertices), 2))
    _attr(ob, "gEdge", np.full(len(ob.data.vertices), 0.2))
    # lenses (H only; reflection layer): two discs inside the rims
    bm = bmesh.new()
    for side in ("L", "R"):
        c = rims[side]
        t = bmesh.ops.create_circle(bm, cap_ends=True, radius=R * 0.98, segments=32)
        for v in t["verts"]:
            x, y, z = v.co
            v.co = Vector((c[0] + x, c[1] + 0.0004, c[2] + y))
    me = bpy.data.meshes.new("lens")
    bm.to_mesh(me)
    bm.free()
    lens = bpy.data.objects.new("lens", me)
    bpy.context.collection.objects.link(lens)
    _uv_patch(lens, ACC_PATCH["lens"])
    return ob, lens


def make_studs(earsP):
    bm = bmesh.new()
    for side, sg in (("L", 1), ("R", -1)):
        p = earsP[side]
        r = bmesh.ops.create_icosphere(bm, subdivisions=1, radius=0.0022)
        for v in r["verts"]:
            v.co += Vector((p[0] + sg * 0.0012, p[1] - 0.0015, p[2] + 0.003))
    me = bpy.data.meshes.new("studs")
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new("studs", me)
    bpy.context.collection.objects.link(ob)
    _uv_patch(ob, ACC_PATCH["gold"])
    _attr(ob, "gLayer", np.full(len(ob.data.vertices), 2))
    _attr(ob, "gEdge", np.full(len(ob.data.vertices), 0.2))
    return ob


def make_bun(look, J, head_top_back):
    """A low bun at the nape: a flattened, slightly twisted sphere of opaque strand texture (opaque core region)."""
    r = look["hair"]["bun"]["radius"]
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=20, v_segments=12, radius=1.0)
    uvl = bm.loops.layers.uv.new("UVMap")
    c = np.array(head_top_back)
    for f in bm.faces:
        for l in f.loops:
            x, y, z = l.vert.co
            ang = math.atan2(y, x)
            # strands spiral around the bun: u along the spiral, v across; mapped into the opaque atlas column
            l[uvl].uv = (0.76 + 0.22 * ((ang / (2 * math.pi) + 0.5 + 0.35 * z) % 1.0), 0.05 + 0.9 * (0.5 + 0.5 * z))
    for v in bm.verts:
        x, y, z = v.co
        v.co = Vector((c[0] + x * r * 1.15, c[1] + y * r * 0.85 + r * 0.25, c[2] + z * r * 0.8))
    me = bpy.data.meshes.new("bun")
    bm.to_mesh(me)
    bm.free()
    for p in me.polygons:
        p.use_smooth = True
    ob = bpy.data.objects.new("bun", me)
    bpy.context.collection.objects.link(ob)
    return ob
