// r3 painted keys (gpt-image-2 edit, c-front as the identity reference): yaw +-25 plates for the turn keyforms and a
// closed / mid lid pair for the blink rebuild. Ledger + hard stop in imgapi.mjs.
//   node scripts/character/puppet2d/polish-r9/gen-keys.mjs <which...>   (yawL yawR closed mid)
import fs from "node:fs";
import { edit, spent } from "./imgapi.mjs";
const K = "art/character/puppet2d/polish-r9/keys";
const SRC = "art/character/puppet2d/polish-r9/c-front.png";
const STYLE = "Identical character, identity, face proportions, colours, matte soft Memoji-style 3D shading, line weight, lighting, hair masses and grooves, gold stud earrings, bindi, teal kurta with orange piping, plain warm-cream background. No text.";
const JOBS = {
  // r4 (judge r3 fix 3): yawR-0 put the bun on the wrong (left) side. Masked edit OF yawR-0 around the two bun areas only
  // (keys/bunmask-R.png); bunfix.py composites just the masked region back, so every hand-read landmark stays valid.
  yawRbun: { images: [{ file: `${K}/yawR-0.png`, name: "yawR.png" }, { file: SRC, name: "front.png" }], mask: `${K}/bunmask-R.png`, prompt: `Image 1 shows the character with her head turned toward the right edge of the image. Her low hair bun is wrongly painted on the LEFT side of her neck. Fix only that: remove the bun from the left side (there, show only the back of her dark hair ending neatly above her neck and the thin loose lock of hair hanging by her left cheek, with the plain warm-cream background around it), and place the same round low bun on the RIGHT side behind her neck, mostly hidden behind her head and neck so only its rounded outer part peeks out at the lower right of her head, as in image 2 where the bun sits at the lower right. Keep the thin loose lock on the right hanging in front. ${STYLE}` },
  // r4 (judge r3 fix 5): the mid-blink key moves from a half lid (a still read as sleepy / smug) to a ~0.62 squeeze
  mid62: { images: [{ file: SRC, name: "front.png" }], mask: `${K}/eyemask.png`, prompt: `The same image caught in the middle of a quick blink: both upper eyelids have come down about two thirds of the way, covering the top of the iris and the upper part of the pupil; only the lower part of each iris and pupil and a sliver of white show below the lowered lid; the lower eyelids are lifted slightly, as in a fast squeeze. Each lowered lid is a smooth rounded skin-coloured lid with a soft crease above it and the dark lash line along its edge with the same outer flick. It must read as motion, a blink in progress, not sleepy and not smug. Brows untouched. ${STYLE}` },
  // r4b (blind r4a 3/3: "features slide in a frontal skull"): the r3 plates were asked for "a small turn" and read ~12-15
  // degrees. A clear three-quarter key, reached at the contract's +-20 limit (painted, never extrapolated).
  yawL30: { images: [{ file: SRC, name: "front.png" }, { file: `${K}/yawL-0.png`, name: "small-turn.png" }, { file: `${K}/q3-left.png`, name: "three-quarter.png" }], prompt: `Image 1 is the character facing the viewer. Image 2 is the same character with a SMALL head turn; image 3 a full three-quarter view. Repaint image 1 with ONLY her head turned about 35 degrees toward the LEFT edge of the image: clearly more turned than image 2, a little less than image 3. The skull and hair rotate with the face: the hair parting moves toward the far (left) side, the near (right) cheek and jaw fill more of the face, the far cheek outline comes in close to the far eye, the nose points left and its tip sits near the far cheek outline without breaking it, the far eye narrower (about three quarters of the near eye's width), her right ear fully visible, the low bun shows clearly behind her neck at the lower right. Shoulders, neck base and kurta exactly as in image 1; the same framing, size and position as image 1; she looks where her face points; gentle closed-mouth smile exactly like image 1. ${STYLE}` },
  yawR30: { images: [{ file: SRC, name: "front.png" }, { file: `${K}/yawR-2.png`, name: "small-turn.png" }, { file: `${K}/q3-right.png`, name: "three-quarter.png" }], prompt: `Image 1 is the character facing the viewer. Image 2 is the same character with a SMALL head turn; image 3 a full three-quarter view. Repaint image 1 with ONLY her head turned about 35 degrees toward the RIGHT edge of the image: clearly more turned than image 2, a little less than image 3. The skull and hair rotate with the face: the hair parting moves toward the far (right) side, the near (left) cheek and jaw fill more of the face, the far cheek outline comes in close to the far eye, the nose points right and its tip sits near the far cheek outline without breaking it, the far eye narrower (about three quarters of the near eye's width), her left ear fully visible; the low bun is mostly hidden behind her neck, only its rounded edge peeking out at the right of her neck. Shoulders, neck base and kurta exactly as in image 1; the same framing, size and position as image 1; she looks where her face points; gentle closed-mouth smile exactly like image 1. ${STYLE}` },
  yawL: { images: [{ file: SRC, name: "front.png" }, { file: `${K}/q3-left.png`, name: "pose.png" }], prompt: `Image 1 is the character, image 2 shows the same character from a three-quarter view. Repaint image 1 with ONLY her head turned about 25 degrees toward the LEFT edge of the image (a small turn: less than image 2; both eyes fully visible, the far eye only slightly narrower), shoulders, neck and kurta exactly as in image 1, the same framing, size and position as image 1, looking where her face points, gentle closed-mouth smile exactly like image 1. ${STYLE}` },
  yawR: { images: [{ file: SRC, name: "front.png" }, { file: `${K}/q3-right.png`, name: "pose.png" }], prompt: `Image 1 is the character, image 2 shows the same character from a three-quarter view. Repaint image 1 with ONLY her head turned about 25 degrees toward the RIGHT edge of the image (a small turn: less than image 2; both eyes fully visible, the far eye only slightly narrower), shoulders, neck and kurta exactly as in image 1, the same framing, size and position as image 1, looking where her face points, gentle closed-mouth smile exactly like image 1. ${STYLE}` },
  closed: { images: [{ file: SRC, name: "front.png" }], mask: `${K}/eyemask.png`, prompt: `The same image with both eyes gently CLOSED in a relaxed blink: the upper eyelids come all the way down; each closed eye is a soft smooth skin-coloured lid with a single clean dark curved lash line (curving downward, a gentle smile-shaped arc) at about two thirds of the eye's height, with the same small outer lash flick, a faint soft crease above the lid. No eyeball, iris or white visible. Brows untouched. ${STYLE}` },
  mid: { images: [{ file: SRC, name: "front.png" }], mask: `${K}/eyemask.png`, prompt: `The same image mid-blink: both upper eyelids lowered to HALF of the eye opening, a smooth rounded skin-coloured lid with a soft natural crease above it, the dark lash line along the lowered lid edge with the same outer flick; the lower half of the iris and the white still visible below the lid, the iris looking straight ahead. Relaxed, not sleepy. Brows untouched. ${STYLE}` },
};
const which = process.argv.slice(2);
for (const w of which) {
  const J = JOBS[w];
  const n = fs.readdirSync(K).filter((f) => f.startsWith(w + "-")).length;
  const buf = await edit({ tag: `r4-key-${w}`, prompt: J.prompt, images: J.images, mask: J.mask || null, quality: "high", size: "1024x1024", fidelity: "high" });
  fs.writeFileSync(`${K}/${w}-${n}.png`, buf);
  console.log("wrote", `${K}/${w}-${n}.png`, "spent", spent().toFixed(2));
}
