// Teaching kits from data/kits/c{class}-{subject}.json (schema: data/kits/SCHEMA.md).
// Kits are generated by another workflow WHILE this code runs, so a file may be missing, half-written,
// or carry partial topics: every read re-checks mtime, a parse failure keeps the last good copy, and
// normalizeKit() drops what cannot be taught safely instead of trusting the shape.
import { readFileSync, readdirSync, statSync } from "fs";
import { resolve } from "path";
import { pathToFileURL } from "url";
import { createHash } from "crypto";
import { checkFits, HINT_TOKEN_MAX } from "../compiler/compile.js";
import { diagnosticItem, revealsAnswer } from "../director/items.js";
import { estimateTokens } from "../learner/brief.js";

const DEFAULT_DIR = new URL("../../data/kits/", import.meta.url);
/** TAXILA_KITS_DIR points the loader at another directory (tests: a kit file appearing mid-lesson). Read per call. */
const kitsDir = () => (process.env.TAXILA_KITS_DIR ? pathToFileURL(resolve(process.env.TAXILA_KITS_DIR) + "/") : DEFAULT_DIR);
const ITEM_KINDS = new Set(["practice", "near_transfer", "far_transfer", "predict", "contrast", "why", "teachback", "retrieval", "error_spot", "translate_rep"]);
const TOPIC_TYPES = new Set(["T1", "T2", "T3", "T4", "T5"]);
const FORMATS = new Set(["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8"]);
/** A kit with fewer non-teachback items than this cannot run a practice phase. */
export const MIN_USABLE_ITEMS = 4;
/**
 * Accepted answer forms kept per item. Every form is pinned in the lesson section beside the key, which
 * nothing may shed: an unbounded list could push it over its cap and throw mid-lesson.
 */
export const ACCEPTABLE_MAX = 8;
const ACCEPTABLE_CHARS = 60;

/** Rung shapes used when a kit item ships fewer than four hints, or a hint failed the lint. Shapes, never lines. */
export const RUNG_DEFAULTS = [
  "pump: a nudge question about what the question asks; no new information",
  "hint: point at the one idea that unlocks it",
  "prompt: a fill-in-the-blank with the key step",
  "assertion: say the answer plainly with a one-line reason",
];

const str = (v) => (typeof v === "string" ? v.trim() : "");
const strArr = (v) => (Array.isArray(v) ? v.map(str).filter(Boolean) : []);

/** Content hash of a normalized kit: a lesson pins the exact kit it started on (content/index.js). */
export const kitHash = (kit) => createHash("sha256").update(JSON.stringify({ ...kit, hash: undefined, lint: undefined })).digest("hex").slice(0, 16);

/**
 * Validate and fill a raw kit topic into a TopicKit the director can rely on, or null if unusable.
 * Items with a disputed key (verified.agrees === false) are dropped: a wrong key teaches the wrong thing.
 * The prompt budget is enforced HERE, at load, so it fails a kit and never a lesson: an item or a
 * diagnostic whose question cannot be pinned in the appended-last section (compile.js checkFits) is
 * dropped. A rung 1-3 hint that states the key (the leak predicate on the hint itself) or that is too long
 * for a voice branch is replaced by the default rung shape — on the text lane such a hint tripped the
 * leak guard and was silently lost. `lint` counts what was dropped or replaced.
 * @param {any} raw
 * @param {{ topicId: string, verified: boolean }} meta
 * @returns {import("../../shared/contracts").TopicKit | null}
 */
export function normalizeKit(raw, { topicId, verified }) {
  if (!raw || typeof raw !== "object") return null;
  let skills = (Array.isArray(raw.skills) ? raw.skills : [])
    .filter((s) => str(s?.id) && str(s?.title))
    .map((s) => ({ id: str(s.id), title: str(s.title), prereqSkillIds: strArr(s.prereqSkillIds) }));
  if (!skills.length) skills = [{ id: `${topicId}-s1`, title: str(raw.title) || topicId, prereqSkillIds: [] }];
  const skillIds = new Set(skills.map((s) => s.id));

  const misconceptions = (Array.isArray(raw.misconceptions) ? raw.misconceptions : [])
    .filter((m) => str(m?.id) && str(m?.belief))
    .map((m) => {
      const d = m.diagnostic;
      const options = Array.isArray(d?.options)
        ? d.options.filter((o) => str(o?.text)).map((o) => ({ text: str(o.text), misconceptionId: str(o.misconceptionId) || null, correct: !!o.correct }))
        : [];
      const diagnosticOk = (str(d?.prompt_en) || str(d?.prompt_hi)) && options.length >= 2 && options.filter((o) => o.correct).length === 1;
      return {
        id: str(m.id), belief: str(m.belief), signs: strArr(m.signs),
        diagnostic: diagnosticOk
          ? { prompt_en: str(d.prompt_en) || str(d.prompt_hi), prompt_hi: str(d.prompt_hi) || str(d.prompt_en), options }
          : null,
        remediation: {
          representation: str(m.remediation?.representation) || "real objects, then a picture",
          moveShape: str(m.remediation?.moveShape) || "show both with objects; let them compare; then ask again",
        },
      };
    });
  const misIds = new Set(misconceptions.map((m) => m.id));
  const lint = { itemsDropped: 0, diagnosticsDropped: 0, hintsReplaced: 0 };

  const items = (Array.isArray(raw.items) ? raw.items : [])
    .filter((it) => str(it?.id) && skillIds.has(str(it?.skillId)) && ITEM_KINDS.has(it?.kind) && str(it?.answer)
      && (str(it?.prompt_en) || str(it?.prompt_hi)) && it?.verified?.agrees !== false)
    .map((it) => {
      const d = Number(it.difficulty);
      const item = {
        id: str(it.id), skillId: str(it.skillId), kind: it.kind,
        difficulty: d >= 1 && d <= 5 ? Math.round(d) : 2,
        prompt_en: str(it.prompt_en) || str(it.prompt_hi), prompt_hi: str(it.prompt_hi) || str(it.prompt_en),
        answer: str(it.answer),
        acceptable: [...new Set(strArr(it.acceptable))].filter((a) => a.length <= ACCEPTABLE_CHARS).slice(0, ACCEPTABLE_MAX), hints: strArr(it.hints).slice(0, 4),
        ...(misIds.has(str(it.targetsMisconception)) ? { targetsMisconception: str(it.targetsMisconception) } : {}),
        ...(it.verified ? { verified: it.verified } : {}),
      };
      item.hints = item.hints.map((h, rung) => {
        const bad = estimateTokens(h) > HINT_TOKEN_MAX || (rung < 3 && revealsAnswer(h, item));
        if (bad) lint.hintsReplaced += 1;
        return bad ? RUNG_DEFAULTS[rung] : h;
      });
      while (item.hints.length < 4) item.hints.push(RUNG_DEFAULTS[item.hints.length]);
      return item;
    })
    .filter((it) => checkFits(it) || !(lint.itemsDropped += 1));
  if (items.filter((i) => i.kind !== "teachback").length < MIN_USABLE_ITEMS) return null;
  // A diagnostic is posed through the same pinned check as an item (its anchor needs the items above).
  for (const m of misconceptions) {
    if (m.diagnostic && !checkFits(diagnosticItem({ items }, m))) { m.diagnostic = null; lint.diagnosticsDropped += 1; }
  }

  const we = raw.workedExample;
  const formats = raw.formats || {};
  const kit = {
    topicId, topicType: TOPIC_TYPES.has(raw.topicType) ? raw.topicType : "T3",
    skills, expectations: strArr(raw.expectations), misconceptions, items,
    workedExample: str(we?.problem) && strArr(we?.steps).length
      ? { problem: str(we.problem), steps: strArr(we.steps), fadedVersion: strArr(we.fadedVersion) }
      : null,
    formats: {
      primary: FORMATS.has(formats.primary) ? formats.primary : "F1",
      secondary: strArr(formats.secondary), engineHints: strArr(formats.engineHints),
    },
    interestContexts: strArr(raw.interestContexts),
    verified,
  };
  return { ...kit, hash: kitHash(kit), lint };
}

/**
 * file URL → { mtimeMs, topics: Map<topicId, raw>, normalized: Map<topicId, TopicKit|null> } — the last copy
 * that parsed, and its topics normalized on first use (normalizeKit runs checkFits over every lane,
 * language and age band: ~3.4 ms a topic, measured, and several lookups a request).
 */
const files = new Map();

function readKitFile(file) {
  const url = new URL(file, kitsDir());
  let st;
  try { st = statSync(url); } catch { return null; }
  const prev = files.get(url.href);
  if (prev && prev.mtimeMs === st.mtimeMs) return prev;
  try {
    const d = JSON.parse(readFileSync(url, "utf8"));
    const topics = new Map((Array.isArray(d.topics) ? d.topics : []).filter((t) => str(t?.topicId)).map((t) => [t.topicId, t]));
    const entry = { mtimeMs: st.mtimeMs, topics, normalized: new Map() };
    files.set(url.href, entry);
    return entry;
  } catch {
    // Mid-write or malformed: keep serving the last good parse; try again when mtime moves.
    if (prev) { prev.mtimeMs = st.mtimeMs; return prev; }
    return null;
  }
}

/** Normalized kit from the class×subject file, or null if the file/topic is missing or unusable. */
export function kitFromFile(topic) {
  const entry = readKitFile(`c${topic.classLevel}-${topic.subject}.json`);
  const raw = entry?.topics.get(topic.id);
  if (!raw) return null;
  if (!entry.normalized.has(topic.id)) entry.normalized.set(topic.id, normalizeKit(raw, { topicId: topic.id, verified: true }));
  return entry.normalized.get(topic.id);
}

let idIndex = { signature: "", map: new Map() };

/** skillId / misconceptionId → topicId across every kit file on disk; rebuilt only when a file changes. */
export function kitIdIndex() {
  let names = [];
  try { names = readdirSync(kitsDir()).filter((f) => /^c\d+-[a-z]+\.json$/.test(f)).sort(); } catch { return idIndex.map; }
  const entries = names.map((f) => [f, readKitFile(f)]);
  const signature = `${kitsDir().href}:` + entries.map(([f, e]) => `${f}@${e?.mtimeMs ?? 0}`).join("|");
  if (signature === idIndex.signature) return idIndex.map;
  const map = new Map();
  for (const [, e] of entries) {
    for (const [topicId, t] of e?.topics ?? []) {
      for (const s of t.skills || []) if (str(s?.id)) map.set(s.id, topicId);
      for (const m of t.misconceptions || []) if (str(m?.id)) map.set(m.id, topicId);
    }
  }
  idIndex = { signature, map };
  return map;
}
