// Item → activity derivation: the truth-bearing half of a G1 fill, written by CODE from the verified kit item
// (FACTORY.md §4.8: "the planner writes intent only; truth-bearing fields are generated by the kit"). A model
// never touches anything here. Each activity carries its own key and a GradeEntry (key, acceptable, distractors
// with kit misconception ids) that stays server-side.
import { fractionTask, keyValues, eq, str, R, cmp, lcm, miscDistractors, parseValue } from "./kitmath.js";

/** Normalised text for key comparisons (case, quotes, trailing punctuation, spaces). */
export const normText = (s) => String(s ?? "").toLowerCase().replace(/[“”"'’‘`]/g, "").replace(/[.!?।]+$/u, "").replace(/\s+/g, " ").trim();

/** Case- and punctuation-preserving form for English keys: capitals and apostrophes ARE the answer in grammar items
 *  ("Kerala" vs "kerala", "soldiers" vs "soldier's"), so only spacing, curly quotes and a final full stop are folded. */
export const strictText = (s) => String(s ?? "").replace(/[’‘]/g, "'").replace(/[“”]/g, '"').replace(/\s+/g, " ").trim().replace(/[.!?।]+$/u, "");

/** The kit's diagnostics as items: the director's own pseudo-item id convention `diag:<misconceptionId>`. */
export function diagnosticItems(kit) {
  return kit.misconceptions.filter((m) => m.diagnostic?.options?.filter((o) => o.correct).length === 1).map((m) => {
    const correct = m.diagnostic.options.find((o) => o.correct);
    const anchor = kit.items.find((i) => i.targetsMisconception === m.id) ?? kit.items[0];
    return { id: `diag:${m.id}`, skillId: anchor?.skillId, kind: "contrast", difficulty: 2, prompt_en: m.diagnostic.prompt_en,
      prompt_hi: m.diagnostic.prompt_hi, answer: correct.text, acceptable: [], targetsMisconception: m.id, diagnostic: true,
      options: m.diagnostic.options, hints: ["", "", "", ""] };
  });
}

// ───────────── fraction-bars@1 (T1 engine) ─────────────
/** A kit answer that says two fractions are equal. */
export const SAME_RE = /\b(same|equal|equivalent|barabar|neither|both are)\b/i;
const MAX_PARTS = 12;
/**
 * Engine params for a fraction task, or a reason it cannot be shown on bars. Params use only fraction-bars@1's
 * declared params (an unknown param makes the frame report params_adjusted).
 */
export function barsActivity(item, kit) {
  if (item.kind === "why" || item.kind === "teachback") return { ok: false, why: "explanation_item" };   // a bar cannot grade a reason
  const task = fractionTask(item);
  if (!task) return { ok: false, why: "not_a_fraction_task" };
  const kv = keyValues(item);
  if (!kv.length && task.op !== "compare") return { ok: false, why: "kit_answer_not_a_value" };
  const proper = (f) => f.n >= 0 && f.n <= f.d && f.d >= 1 && f.d <= MAX_PARTS;
  let params, key = task.key;
  if (task.op === "compare") {
    if (!task.operands.every(proper)) return { ok: false, why: "outside_bars_domain" };
    // Equal fractions: the engine's "same" button is the answer, so the kit must say so in words.
    if (!task.key && !SAME_RE.test(String(item.answer))) return { ok: false, why: "compare_equal_unkeyed" };
    // Day 0 (RS-6 overlay merge): the kit key must name the bigger/smaller fraction itself. "Team Pune, by 1 slice"
    // (c4-maths-ch05-t01-rl-h3) asks for a count, which the bars cannot grade; the G1 gate refused it at
    // truth.kit_answer_not_a_value, so derive never offers it.
    if (task.key && !kv.some((k) => eq(k, task.key))) return { ok: false, why: "kit_answer_not_the_compared_value" };
    params = { mode: "compare", denominators: task.operands.map((f) => f.d), numerators: task.operands.map((f) => f.n), question: task.question, showLabels: true };
  } else if (task.op === "equiv") {
    const [a] = task.operands; const T = task.target;
    if (!proper(a) || !proper(T)) return { ok: false, why: "outside_bars_domain" };
    params = { mode: "shade", denominators: [a.d, T.d], numerators: [a.n, 0], locked: [true, false], target: `${T.n}/${T.d}`, targetBar: 1, equivalentOk: true, showLabels: true };
  } else {
    const [a, b] = task.operands;
    if (!proper(a) || !proper(b) || !key || key.n < 0 || cmp(key, R(1, 1)) > 0) return { ok: false, why: "outside_bars_domain" };
    const L = lcm(a.d, b.d);
    if (L > MAX_PARTS) return { ok: false, why: "outside_bars_domain" };
    const tn = (key.n * L) / key.d;
    if (!Number.isInteger(tn)) return { ok: false, why: "outside_bars_domain" };
    // Both operands as locked reference bars, the result shaded by the child on a bar cut in the common unit.
    params = { mode: "shade", denominators: [a.d, b.d, L], numerators: [a.n, b.n, 0], locked: [true, true, false], target: `${tn}/${L}`, targetBar: 2, equivalentOk: true, showLabels: true };
  }
  const distractors = miscDistractors(task, kit.misconceptions);
  return {
    ok: true, tier: "T1", renderer: "fraction-bars@1", task,
    params,
    // The graded form is what the child produces: the shaded target (equivalence: n/T, not the reduced operand).
    grade: { key: task.op === "equiv" ? `${task.target.n}/${task.target.d}` : key ? str(key) : "same", acceptable: kv.map(str), distractors, keyBasis: "kitmath" },
    childStrings: [],
  };
}

// ───────────── choice (diagnostics and "Which is right: 'A' or 'B'?") ─────────────
/** Options with exactly one correct, from a diagnostic or a two-way contrast prompt. */
export function choiceActivity(item, kit) {
  let options, correct;
  if (item.diagnostic) {
    options = item.options.map((o) => ({ text: o.text, misc: o.misconceptionId || null, correct: !!o.correct }));
  } else {
    const q = [...String(item.prompt_en).matchAll(/['‘’"“”]([^'‘’"“”]{1,80})['‘’"“”]/g)].map((m) => m[1].trim());
    if (q.length !== 2 || !/\b(which|kaun)\b/i.test(item.prompt_en) || !/\bor\b|\bya\b/i.test(item.prompt_en)) return { ok: false, why: "no_closed_options" };
    const want = [item.answer, ...(item.acceptable || [])].map(strictText);
    const hits = q.map((t) => want.includes(strictText(t)));
    if (hits.filter(Boolean).length !== 1) return { ok: false, why: "key_not_an_option" };
    options = q.map((t, i) => ({ text: t, misc: hits[i] ? null : item.targetsMisconception || null, correct: hits[i] }));
  }
  if (options.length < 2 || options.filter((o) => o.correct).length !== 1) return { ok: false, why: "no_single_key" };
  correct = options.findIndex((o) => o.correct);
  return {
    ok: true, tier: "T2a", renderer: "scene@1", template: "choice-card@1",
    options, correct,
    grade: { key: options[correct].text, acceptable: [], distractors: options.filter((o) => !o.correct).map((o) => ({ value: o.text, misc: o.misc || "other" })), keyBasis: item.diagnostic ? "kit_diagnostic" : "kit_answer" },
  };
}

// ───────────── order ("Put these in order: (a) … (b) …" → "c, b, d, a") ─────────────
export function orderActivity(item) {
  const p = String(item.prompt_en);
  if (!/\b(order|sequence|arrange)\b/i.test(p)) return { ok: false, why: "not_an_order_task" };
  const parts = [...p.matchAll(/\(([a-f])\)\s*([^()]+?)(?=\s*\([a-f]\)|$)/g)].map((m) => ({ id: m[1], label: m[2].trim().replace(/[.;,]\s*$/, "") }));
  if (parts.length < 3 || parts.length > 6) return { ok: false, why: "order_size" };
  const letters = String(item.answer).toLowerCase().match(/\b[a-f]\b/g) || [];
  const ids = parts.map((x) => x.id);
  if (letters.length !== parts.length || new Set(letters).size !== letters.length || !letters.every((l) => ids.includes(l))) return { ok: false, why: "key_not_a_permutation" };
  return {
    ok: true, tier: "T2a", renderer: "scene@1", template: "sequence-steps@1",
    steps: parts, key: letters,
    grade: { key: letters.join(","), acceptable: [], distractors: [], keyBasis: "kit_answer" },
  };
}

// ───────────── sentence scramble (English: the kit's own correct sentence, words to put in order) ─────────────
export function scrambleActivity(item, kit) {
  if (!kit.formats.engineHints.some((h) => /scramble|word-order|sentence/i.test(h))) return { ok: false, why: "no_scramble_hint" };
  const sentence = String(item.answer).trim();
  if (!/^[A-Z][A-Za-z ,'’-]+[.!?]$/.test(sentence)) return { ok: false, why: "answer_not_a_sentence" };
  const words = sentence.replace(/[.!?]$/, "").split(/\s+/);
  if (words.length < 3 || words.length > 6) return { ok: false, why: "scramble_size" };
  if (new Set(words.map((w) => w.toLowerCase())).size !== words.length) return { ok: false, why: "ambiguous_key_repeated_word" };
  return {
    ok: true, tier: "T2a", renderer: "scene@1", template: "sequence-steps@1",
    steps: words.map((w, i) => ({ id: `w${i + 1}`, label: w })), key: words.map((_, i) => `w${i + 1}`), sentence,
    grade: { key: sentence, acceptable: [], distractors: [], keyBasis: "kit_answer" },
  };
}

/** Every activity this item can become, in the router's preference order (engines first: content-live-tiers). */
export function activitiesFor(item, kit) {
  const out = [];
  const rejects = [];
  for (const f of [barsActivity, choiceActivity, orderActivity, scrambleActivity]) {
    const a = f(item, kit);
    if (a.ok) out.push(a); else rejects.push(`${f.name}:${a.why}`);
  }
  return { activities: out, rejects };
}

export { parseValue, eq };
