// Synthesize the moon-phases narration once and write MEASURED durations for the timeline.
//   NODE_USE_ENV_PROXY=1 node prototypes/reset/studio/tools/narrate.mjs
// Uses server/azure.js tts() (the product's call, Azure gpt-4o-mini-tts, Azure grant). Keys from .env.local, never printed.
// Output: 03-moon-phases/audio/Lxx.mp3 + 03-moon-phases/narration.js (window.__narration, file:// friendly).
import fs from "node:fs";
import path from "node:path";
import { execFileSync, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../../../..");
process.chdir(repo);
for (const line of fs.readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
}
const { tts } = await import(path.join(repo, "server/azure.js"));
const dir = path.resolve(here, "../03-moon-phases");
const src = JSON.parse(fs.readFileSync(path.join(dir, "narration-src.json"), "utf8"));
const out = path.join(dir, "audio");
fs.mkdirSync(out, { recursive: true });
const lines = {};
let chars = 0;
for (const [id, text] of Object.entries(src.lines)) {
  const f = path.join(out, `${id}.mp3`);
  if (!fs.existsSync(f)) {
    const t0 = Date.now();
    const buf = await tts(text, src.voice, src.instructions);
    fs.writeFileSync(f, Buffer.from(buf));
    console.log(`${id} ${Date.now() - t0} ms`);
    chars += text.length;
  }
  const dur = +execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f]).toString().trim();
  // lead/tail silence and internal pauses (clause boundaries), so cues anchor to speech rather than padding
  const txt = spawnSync("ffmpeg", ["-hide_banner", "-i", f, "-af", "silencedetect=noise=-38dB:d=0.10", "-f", "null", "-"], { encoding: "utf8" }).stderr || "";
  const starts = [...txt.matchAll(/silence_start: ([\d.]+)/g)].map((m) => +m[1]);
  const ends = [...txt.matchAll(/silence_end: ([\d.]+)/g)].map((m) => +m[1]);
  const lead = starts.length && starts[0] < 0.05 && ends.length ? ends[0] : 0;
  let tail = 0;
  if (starts.length > ends.length) tail = dur - starts[starts.length - 1];                  // trailing silence runs to EOF
  else if (ends.length && ends[ends.length - 1] >= dur - 0.06) tail = dur - starts[starts.length - 1];
  const pauses = [];
  for (let i = 0; i < Math.min(starts.length, ends.length); i++) {
    if (starts[i] <= lead + 0.01 || ends[i] >= dur - tail - 0.01) continue;
    pauses.push([+starts[i].toFixed(3), +ends[i].toFixed(3)]);
  }
  lines[id] = { text, file: `audio/${id}.mp3`, dur: +dur.toFixed(3), lead: +lead.toFixed(3), tail: +tail.toFixed(3), pauses };
}
const meta = { model: process.env.DEPLOY_TTS || "gpt-4o-mini-tts", voice: src.voice, date: new Date().toISOString().slice(0, 10), method: "ffprobe duration + ffmpeg silencedetect(-38 dB, 100 ms) for lead/tail/clause pauses", lines };
fs.writeFileSync(path.join(dir, "narration.js"), "/* generated by tools/narrate.mjs: measured narration timing (do not edit by hand) */\nwindow.__narration = " + JSON.stringify(meta, null, 1) + ";\n");
const total = Object.values(lines).reduce((a, b) => a + b.dur, 0);
console.log(`lines ${Object.keys(lines).length}, audio ${total.toFixed(1)} s, new chars ${chars}`);
