"""Garments, accessories and the hair bun, generated by script from the character's own bust surface.

Garments are offset shells of the skin below a per-look neckline (no cloth simulation, AVATAR S9: unmorphed, split
at the collar), with an extruded rolled edge so the fabric reads as having thickness. Each shell carries per-vertex
attributes the texture stage paints from: `gLayer` (0 inner, 1 outer, 2 accessory), `gEdge` (distance in metres to
the nearest open edge, for piping / borders / hems), and cylindrical UVs so weaves and checks keep a constant scale.
"""
import math
import numpy as np
import bpy, bmesh
from mathutils import Vector
from mpfb_env import co, smoothstep, delete_verts

ACC_PATCH = {"metal": (0.905, 0.955), "gold": (0.955, 0.955), "lens": (0.905, 0.905)}   # uv texel centres in the garment atlas


def _cyl(P, ctr):
    th = np.arctan2(P[:, 0] - ctr[0], -(P[:, 1] - ctr[1]))      # 0 = front, +pi/2 = character's left
    return th


def _shell(src, faces_mask, offset, name):
    """Duplicate the faces of `src` (an object) where faces_mask, offset along vertex normals, return the object."""
    me = src.data
    P = co(me)
    N = np.empty(len(me.vertices) * 3)
    me.vertices.foreach_get("normal", N)
    N = N.reshape(-1, 3)
    bm = bmesh.new()
    vmap = {}
    for i, p in enumerate(me.polygons):
        if not faces_mask[i]:
            continue
        vs = []
        for vi in p.vertices:
            if vi not in vmap:
                vmap[vi] = bm.verts.new(Vector(P[vi] + N[vi] * offset))
            vs.append(vmap[vi])
        bm.faces.new(vs)
    out = bpy.data.meshes.new(name)
    bm.to_mesh(out)
    bm.free()
    ob = bpy.data.objects.new(name, out)
    bpy.context.collection.objects.link(ob)
    return ob, np.array(sorted(vmap, key=lambda k: vmap[k].index)) if False else None


def _edge_distance(ob):
    """Graph distance (metres) from every vertex to the nearest boundary vertex (Dijkstra over mesh edges)."""
    import heapq
    me = ob.data
    P = co(me)
    bm = bmesh.new()
    bm.from_mesh(me)
    bnd = [v.index for v in bm.verts if v.is_boundary]
    adj = [[] for _ in range(len(P))]
    for e in bm.edges:
        a, b = e.verts[0].index, e.verts[1].index
        L = float(np.linalg.norm(P[a] - P[b]))
        adj[a].append((b, L))
        adj[b].append((a, L))
    bm.free()
    dist = np.full(len(P), 1e9)
    hq = []
    for b in bnd:
        dist[b] = 0
        hq.append((0.0, b))
    heapq.heapify(hq)
    while hq:
        d, u = heapq.heappop(hq)
        if d > dist[u]:
            continue
        for v, L in adj[u]:
            nd = d + L
            if nd < dist[v]:
                dist[v] = nd
                heapq.heappush(hq, (nd, v))
    return dist, set(bnd)


def _rolled_edge(ob, inward, keep_low_z):
    """Extrude the open top/front edges toward the body by `inward` so the fabric edge has visible thickness."""
    me = ob.data
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.normal_update()
    edges = [e for e in bm.edges if e.is_boundary and min(v.co.z for v in e.verts) > keep_low_z]
    if edges:
        ret = bmesh.ops.extrude_edge_only(bm, edges=edges)
        nv = [g for g in ret["geom"] if isinstance(g, bmesh.types.BMVert)]
        for v in nv:
            n = v.normal if v.normal.length > 0 else Vector((0, 0, 1))
            v.co -= n * inward
    bm.to_mesh(me)
    bm.free()


def _surface_bvh(ob):
    from mathutils.bvhtree import BVHTree
    me = ob.data
    return BVHTree.FromPolygons([v.co.copy() for v in me.vertices], [list(p.vertices) for p in me.polygons])


def _clean_edges(ob, bvh, offset, iters=14, ring_iters=6):
    """Smooth the open edges of a shell along themselves and re-project onto the body at `offset`: the shells are
    cut on whole skin polygons, which left saw-tooth necklines and collars (review item 7)."""
    me = ob.data
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.verts.ensure_lookup_table()
    bnd = [v for v in bm.verts if v.is_boundary]
    nb = {v.index: [e.other_vert(v) for e in v.link_edges if e.is_boundary] for v in bnd}
    ring = {v for b in bnd for e in b.link_edges for v in [e.other_vert(b)] if not v.is_boundary}

    def proj(p):
        loc, n, _, _ = bvh.find_nearest(p)
        return loc + n * offset if loc is not None else p

    for _ in range(iters):
        new = {}
        for v in bnd:
            ns = nb[v.index]
            if len(ns) == 2:
                new[v.index] = proj(v.co * 0.5 + (ns[0].co + ns[1].co) * 0.25)
        for i, c in new.items():
            bm.verts[i].co = c
    for _ in range(ring_iters):
        new = {}
        for v in ring:
            ns = [e.other_vert(v).co for e in v.link_edges]
            avg = sum(ns, Vector((0, 0, 0))) / len(ns)
            new[v.index] = proj(v.co * 0.5 + avg * 0.5)
        for i, c in new.items():
            bm.verts[i].co = c
    bm.to_mesh(me)
    bm.free()
    me.update()


def _push_out(outer, inner, gap):
    """Every outer-layer vertex at least `gap` outside the inner layer (along the inner surface normal)."""
    bvh = _surface_bvh(inner)
    me = outer.data
    P = co(me)
    moved = 0
    for i, p in enumerate(P):
        loc, n, _, d = bvh.find_nearest(Vector(p))
        if loc is None or d > 0.03:
            continue
        s_ = (Vector(p) - loc).dot(n)
        if s_ < gap:
            P[i] = np.array(Vector(p) + n * (gap - s_))
            moved += 1
    me.vertices.foreach_set("co", P.ravel())
    me.update()
    return moved


def penetration(under, over, reach=0.03):
    """Vertices of `under` that sit OUTSIDE `over` where `over` exists: the ray along the under-vertex normal finds
    no `over` surface ahead, but the opposite ray finds it behind within 15 mm. 0 = no poke-through."""
    bvh = _surface_bvh(over)
    me = under.data
    me.update()
    n = 0
    for v in me.vertices:
        p, nn = v.co, v.normal
        ahead = bvh.ray_cast(p + nn * 1e-4, nn, reach)[0]
        if ahead is None and bvh.ray_cast(p - nn * 1e-4, -nn, 0.015)[0] is not None:
            n += 1
    return n


def _cap_arm_holes(ob, x_min):
    """Close the shell's open loops at the bust's arm cut (|x| > x_min) so the turntable never looks into the garment:
    at yaw 90 / 270 the open sleeve showed the kurti and its piping through the jacket (review item 7)."""
    me = ob.data
    bm = bmesh.new()
    bm.from_mesh(me)
    zlow = min(v.co.z for v in bm.verts) + 0.012
    for sg in (1, -1):
        edges = [e for e in bm.edges if e.is_boundary and all(sg * v.co.x > x_min and v.co.z > zlow for v in e.verts)]
        if len(edges) < 3:
            continue
        vs = {v for e in edges for v in e.verts}
        c = bm.verts.new(sum((v.co for v in vs), Vector((0, 0, 0))) / len(vs))
        for e in edges:
            try:
                bm.faces.new([e.verts[0], e.verts[1], c])
            except ValueError:
                pass
    bm.normal_update()
    bm.to_mesh(me)
    bm.free()
    me.update()


def _attr(ob, name, arr):
    a = ob.data.attributes.get(name) or ob.data.attributes.new(name, "FLOAT", "POINT")
    a.data.foreach_set("value", np.asarray(arr, np.float32))


def _cyl_uv(ob, ctr, layer, z0, z1):
    """Cylindrical UV in a per-layer band of the garment atlas: u = theta, v = height (constant texel scale)."""
    me = ob.data
    P = co(me)
    th = _cyl(P, ctr)
    uvl = me.uv_layers.new(name="UVMap")
    v0 = 0.02 + 0.44 * layer
    for p in me.polygons:
        for li, vi in zip(p.loop_indices, p.vertices):
            u = 0.02 + 0.86 * (th[vi] + math.pi) / (2 * math.pi)
            v = v0 + 0.42 * np.clip((P[vi, 2] - z0) / (z1 - z0), 0, 1)
            uvl.data[li].uv = (u, v)


def make_garments(skin, look, J, report):
    """Build the look's garment layers from the bust skin; delete the skin they cover. Returns [objects]."""
    g = look["garment"]
    P = co(skin.data)
    ctr = np.array([0.0, J["joint-neck"][1] + 0.005])
    th = _cyl(P, ctr)
    z_clav = J["joint-l-clavicle"][2]
    zmin = P[:, 2].min()
    front = np.clip(np.cos(th), 0, 1)
    kind = g["kind"]
    base = z_clav + 0.045
    if kind == "kurti-jacket":
        z_col = base - 0.05 * front ** 2
    elif kind == "shirt-tee":
        z_col = base + 0.004 - 0.026 * front ** 3
    else:  # saree blouse
        z_col = base - 0.05 * front ** 2
    covered_v = P[:, 2] < z_col
    polys = skin.data.polygons
    fmask = np.array([all(covered_v[i] for i in p.vertices) for p in polys])
    objs = []

    sbvh = _surface_bvh(skin)
    inner, _ = _shell(skin, fmask, 0.0042, "g_inner")
    _clean_edges(inner, sbvh, 0.0042)
    if kind == "saree":            # the blouse is the visible layer at the arm cut; otherwise the outer layer caps it
        _cap_arm_holes(inner, abs(J["joint-l-shoulder"][0]) - 0.01)
    _rolled_edge(inner, 0.003, zmin + 0.015)
    objs.append((inner, 0))

    def outer_shell(open_half, offset, name, stand=0.0, extra_mask=None):
        th_open = np.radians(open_half)
        m = covered_v & (np.abs(th) > th_open + 0.25 * np.clip((z_col - P[:, 2]) / 0.12, 0, 1))
        if extra_mask is not None:
            m = extra_mask
        fm = np.array([all(m[i] for i in p.vertices) for p in polys])
        ob, _ = _shell(skin, fm, offset, name)
        _clean_edges(ob, sbvh, offset)
        _cap_arm_holes(ob, abs(J["joint-l-shoulder"][0]) - 0.01)
        if stand > 0:   # a standing collar: extrude the neck-side boundary up and slightly out
            bm = bmesh.new()
            bm.from_mesh(ob.data)
            edges = [e for e in bm.edges if e.is_boundary and all(v.co.z > z_clav - 0.01 for v in e.verts)]
            if edges:
                ret = bmesh.ops.extrude_edge_only(bm, edges=edges)
                for v in [x for x in ret["geom"] if isinstance(x, bmesh.types.BMVert)]:
                    d = Vector((v.co.x - ctr[0], v.co.y - ctr[1], 0))
                    d = d.normalized() if d.length > 0 else Vector((0, 1, 0))
                    v.co += Vector((0, 0, stand)) + d * (0.006)
            bm.to_mesh(ob.data)
            bm.free()
        _rolled_edge(ob, 0.004, zmin + 0.015)
        return ob

    if kind == "kurti-jacket":
        objs.append((outer_shell(28, 0.011, "g_outer", stand=0.012), 1))
    elif kind == "shirt-tee":
        objs.append((outer_shell(16, 0.009, "g_outer", stand=0.022), 1))
    else:
        # saree pallu: a separate pleated strip from the right lower chest, over the LEFT shoulder, down the back
        # (TEACHER-VISUAL 4.3), projected onto the body; its border is UV-space trim along the strip's long edges
        objs.append((make_pallu(sbvh, J, z_clav, zmin, g), 1))

    # layers never interpenetrate: outer >= 4 mm outside inner (review item 7, "kurti pokes through the jacket")
    report["garmentPushedVerts"] = 0
    if len(objs) > 1:
        report["garmentPushedVerts"] = _push_out(objs[1][0], objs[0][0], 0.004)

    # delete the skin the garment covers (keep a 1.5 cm skirt under the collar so no gap shows on motion)
    under = P[:, 2] < (z_col - 0.015)
    delete_verts(skin, under)

    zs = (zmin, z_clav + 0.08)
    out = []
    # penetration gate: the inner layer must not show through the outer one, the kept skin skirt not through the inner
    report["garmentPenetration"] = {"innerThroughOuter": penetration(objs[0][0], objs[1][0]) if len(objs) > 1 else 0}
    for ob, layer in objs:
        if "gEdge" in ob.data.attributes:
            _attr(ob, "gLayer", np.full(len(ob.data.vertices), layer))
            if "gOwnUV" not in ob.data.attributes:
                _cyl_uv(ob, ctr, layer, *zs)
            out.append(ob)
            continue
        dist, _ = _edge_distance(ob)
        _attr(ob, "gEdge", np.minimum(dist, 0.2))
        _attr(ob, "gLayer", np.full(len(ob.data.vertices), layer))
        _cyl_uv(ob, ctr, layer, *zs)
        out.append(ob)
    report["garment"] = {"kind": kind, "collarBaseZ": float(base)}
    return out


def make_pallu(sbvh, J, z_clav, zmin, g, n_along=72, n_across=12):
    """The pallu: a strip along a smooth path (front right lower chest -> over the left shoulder -> down the back),
    narrowing where it is gathered on the shoulder, with soft pleat folds, projected onto the bust at a cloth offset.
    gEdge = distance to the strip's LONG edges (so the border is a trim along the edge, not a texture-space band)."""
    yN = J["joint-neck"][1]
    yC = J["joint-l-clavicle"][1]
    ctrl = np.array([[-0.14, yN - 0.11, zmin + 0.01], [-0.02, yN - 0.115, z_clav - 0.07], [0.075, yN - 0.07, z_clav + 0.02],
                     [0.105, yC + 0.01, z_clav + 0.045], [0.085, yC + 0.09, z_clav + 0.01], [0.04, yC + 0.17, zmin + 0.01]])
    pts = ctrl
    for _ in range(4):                                   # Chaikin: a smooth drape path through the control points
        q = [pts[0]]
        for i in range(len(pts) - 1):
            q += [0.75 * pts[i] + 0.25 * pts[i + 1], 0.25 * pts[i] + 0.75 * pts[i + 1]]
        q.append(pts[-1])
        pts = np.array(q)
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    s = np.concatenate([[0], np.cumsum(seg)])
    st = np.linspace(0, s[-1], n_along)
    path = np.stack([np.interp(st, s, pts[:, k]) for k in range(3)], 1)
    W = g.get("palluWidth", 0.18)
    sh_t = s[np.argmin(np.linalg.norm(pts - ctrl[3], axis=1))] / s[-1]
    verts, gEdge, uvs = [], [], []
    for i, p in enumerate(path):
        t = st[i] / s[-1]
        T = path[min(i + 1, n_along - 1)] - path[max(i - 1, 0)]
        T /= np.linalg.norm(T)
        loc, n, _, _ = sbvh.find_nearest(Vector(p))
        n = np.array(n)
        A = np.cross(n, T)
        A /= np.linalg.norm(A)
        gather = np.exp(-((t - sh_t) / 0.12) ** 2)        # gathered (narrow, deeper pleats) on the shoulder
        w = W * (1 - 0.45 * gather)
        for j in range(n_across):
            u = j / (n_across - 1)
            q = p + A * (u - 0.5) * w
            l2, n2, _, _ = sbvh.find_nearest(Vector(q))
            fold = (0.0018 + 0.003 * gather) * np.sin(u * math.pi * (5 + 2 * gather)) ** 2
            v = np.array(l2) + np.array(n2) * (0.0095 + fold)
            verts.append(v)
            gEdge.append((0.5 - abs(u - 0.5)) * w)
    bm = bmesh.new()
    bv = [bm.verts.new(Vector(v)) for v in verts]
    for i in range(n_along - 1):
        for j in range(n_across - 1):
            a, b = i * n_across + j, i * n_across + j + 1
            c, d = (i + 1) * n_across + j + 1, (i + 1) * n_across + j
            bm.faces.new([bv[a], bv[b], bv[c], bv[d]])
    bm.normal_update()
    # outward-facing: flip if the average normal points into the body
    avg = sum((f.normal for f in bm.faces), Vector((0, 0, 0)))
    cen = sum((v.co for v in bm.verts), Vector((0, 0, 0))) / len(bm.verts)
    if avg.dot(cen - Vector((0, yN, cen.z))) < 0:
        bmesh.ops.reverse_faces(bm, faces=bm.faces)
    me = bpy.data.meshes.new("pallu")
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new("pallu", me)
    bpy.context.collection.objects.link(ob)
    _attr(ob, "gEdge", np.array(gEdge))
    # its own strip UVs in the outer band (u along the drape, v across): the cylindrical unwrap squashed the diagonal
    # strip into a thin region and the dilated border colour bled across it in the lower mips (iteration 2)
    uvl = me.uv_layers.new(name="UVMap")
    for p_ in me.polygons:
        for li, vi in zip(p_.loop_indices, p_.vertices):
            i, j = divmod(vi, n_across)
            uvl.data[li].uv = (0.02 + 0.86 * i / (n_along - 1), 0.47 + 0.40 * j / (n_across - 1))
    _attr(ob, "gOwnUV", np.ones(len(me.vertices)))
    return ob


def _uv_patch(ob, uv):
    me = ob.data
    uvl = me.uv_layers.get("UVMap") or me.uv_layers.new(name="UVMap")
    for li in range(len(me.loops)):
        uvl.data[li].uv = uv


def make_glasses(look, eyeC, eyeR, earsP):
    """Round thin-rim glasses: two torus rims, a bridge, two temples to the ears. Rigid to the head."""
    gl = look["accessory"]["glasses"]
    R = gl["radius"]
    bm = bmesh.new()
    rims = {}
    for side, sg in (("L", 1), ("R", -1)):
        c = np.array(eyeC[side]) + np.array([sg * 0.001, -(eyeR + 0.009), 0.001])
        rims[side] = c
        t = bmesh.ops.create_circle(bm, cap_ends=False, radius=R, segments=40)
        ring = t["verts"]
        # orient: circle is in XY; rotate to XZ (facing -Y) and move
        for v in ring:
            x, y, z = v.co
            v.co = Vector((c[0] + x, c[1], c[2] + y))
    me = bpy.data.meshes.new("rims")
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new("glasses", me)
    bpy.context.collection.objects.link(ob)
    # give the rim circles thickness with a skin-like tube: convert edges to a curve bevel
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.ops.object.convert(target="CURVE")
    ob.data.bevel_depth = 0.0011
    ob.data.bevel_resolution = 1
    # bridge + temples as curves too
    cu = bpy.data.curves.new("frame", "CURVE")
    cu.dimensions = "3D"
    cu.bevel_depth = 0.0009
    cu.bevel_resolution = 1

    def poly(points):
        s = cu.splines.new("POLY")
        s.points.add(len(points) - 1)
        for p, q in zip(s.points, points):
            p.co = (*q, 1)

    L, Rr = rims["L"], rims["R"]
    poly([L + np.array([-R, 0, 0.004]), (L + Rr) / 2 + np.array([0, -0.002, 0.009]), Rr + np.array([R, 0, 0.004])])
    for side, sg in (("L", 1), ("R", -1)):
        c = rims[side]
        ear = earsP[side]
        start = c + np.array([sg * R, 0, 0.004])
        poly([start, start + np.array([sg * 0.008, 0.012, 0.0]), np.array([ear[0] + sg * 0.004, ear[1] - 0.004, ear[2] + 0.012]),
              np.array([ear[0] + sg * 0.002, ear[1] + 0.012, ear[2] - 0.004])])
    fo = bpy.data.objects.new("frame", cu)
    bpy.context.collection.objects.link(fo)
    bpy.ops.object.select_all(action="DESELECT")
    fo.select_set(True)
    bpy.context.view_layer.objects.active = fo
    bpy.ops.object.convert(target="MESH")
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.convert(target="MESH")
    fo.select_set(True)
    bpy.ops.object.join()
    _uv_patch(ob, ACC_PATCH["metal"])
    _attr(ob, "gLayer", np.full(len(ob.data.vertices), 2))
    _attr(ob, "gEdge", np.full(len(ob.data.vertices), 0.2))
    # lenses (H only; reflection layer): two discs inside the rims
    bm = bmesh.new()
    for side in ("L", "R"):
        c = rims[side]
        t = bmesh.ops.create_circle(bm, cap_ends=True, radius=R * 0.98, segments=32)
        for v in t["verts"]:
            x, y, z = v.co
            v.co = Vector((c[0] + x, c[1] + 0.0004, c[2] + y))
    me = bpy.data.meshes.new("lens")
    bm.to_mesh(me)
    bm.free()
    lens = bpy.data.objects.new("lens", me)
    bpy.context.collection.objects.link(lens)
    _uv_patch(lens, ACC_PATCH["lens"])
    return ob, lens


def make_studs(earsP):
    bm = bmesh.new()
    for side, sg in (("L", 1), ("R", -1)):
        p = earsP[side]
        r = bmesh.ops.create_icosphere(bm, subdivisions=1, radius=0.0022)
        for v in r["verts"]:
            v.co += Vector((p[0] + sg * 0.0012, p[1] - 0.0015, p[2] + 0.003))
    me = bpy.data.meshes.new("studs")
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new("studs", me)
    bpy.context.collection.objects.link(ob)
    _uv_patch(ob, ACC_PATCH["gold"])
    _attr(ob, "gLayer", np.full(len(ob.data.vertices), 2))
    _attr(ob, "gEdge", np.full(len(ob.data.vertices), 0.2))
    return ob


def make_bun(look, J, head_top_back):
    """A low bun at the nape: a flattened, slightly twisted sphere of opaque strand texture (opaque core region)."""
    r = look["hair"]["bun"]["radius"]
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=20, v_segments=12, radius=1.0)
    uvl = bm.loops.layers.uv.new("UVMap")
    c = np.array(head_top_back)
    for f in bm.faces:
        for l in f.loops:
            x, y, z = l.vert.co
            ang = math.atan2(y, x)
            # strands spiral around the bun: u along the spiral, v across; mapped into the opaque atlas column
            l[uvl].uv = (0.76 + 0.22 * ((ang / (2 * math.pi) + 0.5 + 0.35 * z) % 1.0), 0.05 + 0.9 * (0.5 + 0.5 * z))
    for v in bm.verts:
        x, y, z = v.co
        v.co = Vector((c[0] + x * r * 1.15, c[1] + y * r * 0.85 + r * 0.25, c[2] + z * r * 0.8))
    me = bpy.data.meshes.new("bun")
    bm.to_mesh(me)
    bm.free()
    for p in me.polygons:
        p.use_smooth = True
    ob = bpy.data.objects.new("bun", me)
    bpy.context.collection.objects.link(ob)
    return ob
