/* generated by tools/narrate.mjs: measured narration timing (do not edit by hand) */
window.__narration = {
 "model": "gpt-4o-mini-tts",
 "voice": "marin",
 "date": "2026-10-04",
 "method": "ffprobe duration + ffmpeg silencedetect(-38 dB, 100 ms) for lead/tail/clause pauses",
 "lines": {
  "L01": {
   "text": "Every evening, the Moon looks a little different.",
   "file": "audio/L01.mp3",
   "dur": 3.408,
   "lead": 0,
   "tail": 0.303,
   "pauses": [
    [
     1.113,
     1.408
    ]
   ]
  },
  "L02": {
   "text": "A thin curve. Half a circle. A full disc. Then back again.",
   "file": "audio/L02.mp3",
   "dur": 6.408,
   "lead": 0,
   "tail": 0.202,
   "pauses": [
    [
     0.653,
     0.824
    ],
    [
     1.328,
     1.82
    ],
    [
     2.771,
     3.189
    ],
    [
     4.205,
     4.94
    ],
    [
     5.303,
     5.67
    ]
   ]
  },
  "L03": {
   "text": "But the Moon itself never changes shape. So what's going on?",
   "file": "audio/L03.mp3",
   "dur": 5.016,
   "lead": 0,
   "tail": 0.205,
   "pauses": [
    [
     0.273,
     0.414
    ],
    [
     1.384,
     1.669
    ],
    [
     2.842,
     3.31
    ],
    [
     3.655,
     4.031
    ]
   ]
  },
  "L04": {
   "text": "Let's go up, and look down from above the North Pole.",
   "file": "audio/L04.mp3",
   "dur": 3.216,
   "lead": 0,
   "tail": 0.342,
   "pauses": [
    [
     0.736,
     1.108
    ]
   ]
  },
  "L05": {
   "text": "Sunlight comes in from one side.",
   "file": "audio/L05.mp3",
   "dur": 2.448,
   "lead": 0,
   "tail": 0.269,
   "pauses": []
  },
  "L06": {
   "text": "The Moon makes no light of its own. The Sun lights up half of it, always the half facing the Sun.",
   "file": "audio/L06.mp3",
   "dur": 6.168,
   "lead": 0,
   "tail": 0.176,
   "pauses": [
    [
     2.114,
     2.592
    ],
    [
     4.005,
     4.333
    ]
   ]
  },
  "L07": {
   "text": "As the Moon travels around the Earth, that lit half keeps facing the Sun.",
   "file": "audio/L07.mp3",
   "dur": 5.112,
   "lead": 0,
   "tail": 0.107,
   "pauses": [
    [
     2.32,
     2.861
    ],
    [
     3.642,
     3.898
    ]
   ]
  },
  "L08": {
   "text": "But from Earth, we only see the half that faces us.",
   "file": "audio/L08.mp3",
   "dur": 4.32,
   "lead": 0,
   "tail": 0.212,
   "pauses": [
    [
     0.202,
     0.408
    ],
    [
     1.207,
     1.649
    ],
    [
     2.956,
     3.223
    ]
   ]
  },
  "L09": {
   "text": "New moon. Amavasya. The lit half faces away, so we see almost nothing.",
   "file": "audio/L09.mp3",
   "dur": 5.952,
   "lead": 0,
   "tail": 0.261,
   "pauses": [
    [
     0.771,
     1.273
    ],
    [
     1.959,
     2.428
    ],
    [
     3.789,
     4.21
    ]
   ]
  },
  "L10": {
   "text": "A few days on, a thin crescent.",
   "file": "audio/L10.mp3",
   "dur": 2.808,
   "lead": 0,
   "tail": 0.235,
   "pauses": [
    [
     1.194,
     1.539
    ]
   ]
  },
  "L11": {
   "text": "About a week in, first quarter. We see half of the lit half.",
   "file": "audio/L11.mp3",
   "dur": 4.056,
   "lead": 0,
   "tail": 0.157,
   "pauses": [
    [
     0.913,
     1.221
    ],
    [
     1.94,
     2.241
    ]
   ]
  },
  "L12": {
   "text": "Two weeks: full moon. Purnima. The whole lit half faces us.",
   "file": "audio/L12.mp3",
   "dur": 6.408,
   "lead": 0.236,
   "tail": 0.574,
   "pauses": [
    [
     0.891,
     1.151
    ],
    [
     1.89,
     2.477
    ],
    [
     2.998,
     3.622
    ],
    [
     4.82,
     5.075
    ]
   ]
  },
  "L13": {
   "text": "Then it shrinks back the same way. One full cycle takes about twenty-nine and a half days.",
   "file": "audio/L13.mp3",
   "dur": 6.36,
   "lead": 0,
   "tail": 0.139,
   "pauses": [
    [
     2.3,
     2.986
    ],
    [
     3.952,
     4.145
    ]
   ]
  },
  "L14": {
   "text": "And no, it isn't Earth's shadow.",
   "file": "audio/L14.mp3",
   "dur": 3.36,
   "lead": 0,
   "tail": 0.185,
   "pauses": [
    [
     0.351,
     0.673
    ],
    [
     0.98,
     1.617
    ],
    [
     1.749,
     1.9
    ],
    [
     2.259,
     2.472
    ]
   ]
  },
  "L15": {
   "text": "Earth's shadow points away from the Sun. At first quarter the Moon is nowhere near it, and half of it is still dark.",
   "file": "audio/L15.mp3",
   "dur": 7.2,
   "lead": 0,
   "tail": 0.545,
   "pauses": [
    [
     1.955,
     2.458
    ],
    [
     4.818,
     5.301
    ]
   ]
  },
  "L16": {
   "text": "The Moon slips into that shadow only now and then, at a full moon. That's a lunar eclipse.",
   "file": "audio/L16.mp3",
   "dur": 6.864,
   "lead": 0,
   "tail": 0.637,
   "pauses": [
    [
     1.912,
     2.085
    ],
    [
     3.012,
     3.316
    ],
    [
     4.17,
     4.779
    ],
    [
     5.151,
     5.339
    ]
   ]
  },
  "L17": {
   "text": "Your turn. Drag the Moon to where it would look like a half moon in the evening sky.",
   "file": "audio/L17.mp3",
   "dur": 5.352,
   "lead": 0.309,
   "tail": 0.302,
   "pauses": [
    [
     0.832,
     1.205
    ],
    [
     3.866,
     4.104
    ]
   ]
  },
  "L18": {
   "text": "That's it. First quarter.",
   "file": "audio/L18.mp3",
   "dur": 2.16,
   "lead": 0,
   "tail": 0.299,
   "pauses": [
    [
     0.689,
     1.136
    ]
   ]
  },
  "L19": {
   "text": "Now make it a full moon.",
   "file": "audio/L19.mp3",
   "dur": 2.304,
   "lead": 0,
   "tail": 0.278,
   "pauses": [
    [
     0.48,
     0.631
    ]
   ]
  },
  "L20": {
   "text": "Full moon. Purnima.",
   "file": "audio/L20.mp3",
   "dur": 3.216,
   "lead": 0.167,
   "tail": 1.033,
   "pauses": [
    [
     1.097,
     1.593
    ]
   ]
  },
  "L21": {
   "text": "That's a half moon too, but a morning one. Try the other side.",
   "file": "audio/L21.mp3",
   "dur": 4.368,
   "lead": 0,
   "tail": 0.327,
   "pauses": [
    [
     1.51,
     1.811
    ],
    [
     2.62,
     3.076
    ]
   ]
  }
 }
};
